FROM golang:1.26.1-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o enterprise-bff ./cmd/enterprise-bff/

EXPOSE 8090

CMD ["./enterprise-bff"]
