// Code generated by ent, DO NOT EDIT.

package promocode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldCode, v))
}

// Scene applies equality check predicate on the "scene" field. It's identical to SceneEQ.
func Scene(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldScene, v))
}

// BonusAmount applies equality check predicate on the "bonus_amount" field. It's identical to BonusAmountEQ.
func BonusAmount(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldBonusAmount, v))
}

// RandomBonusPoolAmount applies equality check predicate on the "random_bonus_pool_amount" field. It's identical to RandomBonusPoolAmountEQ.
func RandomBonusPoolAmount(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldRandomBonusPoolAmount, v))
}

// RandomBonusRemaining applies equality check predicate on the "random_bonus_remaining" field. It's identical to RandomBonusRemainingEQ.
func RandomBonusRemaining(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldRandomBonusRemaining, v))
}

// MaxUses applies equality check predicate on the "max_uses" field. It's identical to MaxUsesEQ.
func MaxUses(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldMaxUses, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldUsedCount, v))
}

// LeaderboardEnabled applies equality check predicate on the "leaderboard_enabled" field. It's identical to LeaderboardEnabledEQ.
func LeaderboardEnabled(v bool) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldLeaderboardEnabled, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldExpiresAt, v))
}

// SuccessMessage applies equality check predicate on the "success_message" field. It's identical to SuccessMessageEQ.
func SuccessMessage(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldSuccessMessage, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContainsFold(FieldCode, v))
}

// SceneEQ applies the EQ predicate on the "scene" field.
func SceneEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldScene, v))
}

// SceneNEQ applies the NEQ predicate on the "scene" field.
func SceneNEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldScene, v))
}

// SceneIn applies the In predicate on the "scene" field.
func SceneIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldScene, vs...))
}

// SceneNotIn applies the NotIn predicate on the "scene" field.
func SceneNotIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldScene, vs...))
}

// SceneGT applies the GT predicate on the "scene" field.
func SceneGT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldScene, v))
}

// SceneGTE applies the GTE predicate on the "scene" field.
func SceneGTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldScene, v))
}

// SceneLT applies the LT predicate on the "scene" field.
func SceneLT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldScene, v))
}

// SceneLTE applies the LTE predicate on the "scene" field.
func SceneLTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldScene, v))
}

// SceneContains applies the Contains predicate on the "scene" field.
func SceneContains(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContains(FieldScene, v))
}

// SceneHasPrefix applies the HasPrefix predicate on the "scene" field.
func SceneHasPrefix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasPrefix(FieldScene, v))
}

// SceneHasSuffix applies the HasSuffix predicate on the "scene" field.
func SceneHasSuffix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasSuffix(FieldScene, v))
}

// SceneEqualFold applies the EqualFold predicate on the "scene" field.
func SceneEqualFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEqualFold(FieldScene, v))
}

// SceneContainsFold applies the ContainsFold predicate on the "scene" field.
func SceneContainsFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContainsFold(FieldScene, v))
}

// BonusAmountEQ applies the EQ predicate on the "bonus_amount" field.
func BonusAmountEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldBonusAmount, v))
}

// BonusAmountNEQ applies the NEQ predicate on the "bonus_amount" field.
func BonusAmountNEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldBonusAmount, v))
}

// BonusAmountIn applies the In predicate on the "bonus_amount" field.
func BonusAmountIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldBonusAmount, vs...))
}

// BonusAmountNotIn applies the NotIn predicate on the "bonus_amount" field.
func BonusAmountNotIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldBonusAmount, vs...))
}

// BonusAmountGT applies the GT predicate on the "bonus_amount" field.
func BonusAmountGT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldBonusAmount, v))
}

// BonusAmountGTE applies the GTE predicate on the "bonus_amount" field.
func BonusAmountGTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldBonusAmount, v))
}

// BonusAmountLT applies the LT predicate on the "bonus_amount" field.
func BonusAmountLT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldBonusAmount, v))
}

// BonusAmountLTE applies the LTE predicate on the "bonus_amount" field.
func BonusAmountLTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldBonusAmount, v))
}

// RandomBonusPoolAmountEQ applies the EQ predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldRandomBonusPoolAmount, v))
}

// RandomBonusPoolAmountNEQ applies the NEQ predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountNEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldRandomBonusPoolAmount, v))
}

// RandomBonusPoolAmountIn applies the In predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldRandomBonusPoolAmount, vs...))
}

// RandomBonusPoolAmountNotIn applies the NotIn predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountNotIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldRandomBonusPoolAmount, vs...))
}

// RandomBonusPoolAmountGT applies the GT predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountGT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldRandomBonusPoolAmount, v))
}

// RandomBonusPoolAmountGTE applies the GTE predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountGTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldRandomBonusPoolAmount, v))
}

// RandomBonusPoolAmountLT applies the LT predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountLT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldRandomBonusPoolAmount, v))
}

// RandomBonusPoolAmountLTE applies the LTE predicate on the "random_bonus_pool_amount" field.
func RandomBonusPoolAmountLTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldRandomBonusPoolAmount, v))
}

// RandomBonusRemainingEQ applies the EQ predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldRandomBonusRemaining, v))
}

// RandomBonusRemainingNEQ applies the NEQ predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingNEQ(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldRandomBonusRemaining, v))
}

// RandomBonusRemainingIn applies the In predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldRandomBonusRemaining, vs...))
}

// RandomBonusRemainingNotIn applies the NotIn predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingNotIn(vs ...float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldRandomBonusRemaining, vs...))
}

// RandomBonusRemainingGT applies the GT predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingGT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldRandomBonusRemaining, v))
}

// RandomBonusRemainingGTE applies the GTE predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingGTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldRandomBonusRemaining, v))
}

// RandomBonusRemainingLT applies the LT predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingLT(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldRandomBonusRemaining, v))
}

// RandomBonusRemainingLTE applies the LTE predicate on the "random_bonus_remaining" field.
func RandomBonusRemainingLTE(v float64) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldRandomBonusRemaining, v))
}

// MaxUsesEQ applies the EQ predicate on the "max_uses" field.
func MaxUsesEQ(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldMaxUses, v))
}

// MaxUsesNEQ applies the NEQ predicate on the "max_uses" field.
func MaxUsesNEQ(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldMaxUses, v))
}

// MaxUsesIn applies the In predicate on the "max_uses" field.
func MaxUsesIn(vs ...int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldMaxUses, vs...))
}

// MaxUsesNotIn applies the NotIn predicate on the "max_uses" field.
func MaxUsesNotIn(vs ...int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldMaxUses, vs...))
}

// MaxUsesGT applies the GT predicate on the "max_uses" field.
func MaxUsesGT(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldMaxUses, v))
}

// MaxUsesGTE applies the GTE predicate on the "max_uses" field.
func MaxUsesGTE(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldMaxUses, v))
}

// MaxUsesLT applies the LT predicate on the "max_uses" field.
func MaxUsesLT(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldMaxUses, v))
}

// MaxUsesLTE applies the LTE predicate on the "max_uses" field.
func MaxUsesLTE(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldMaxUses, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldUsedCount, v))
}

// LeaderboardEnabledEQ applies the EQ predicate on the "leaderboard_enabled" field.
func LeaderboardEnabledEQ(v bool) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldLeaderboardEnabled, v))
}

// LeaderboardEnabledNEQ applies the NEQ predicate on the "leaderboard_enabled" field.
func LeaderboardEnabledNEQ(v bool) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldLeaderboardEnabled, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotNull(FieldExpiresAt))
}

// SuccessMessageEQ applies the EQ predicate on the "success_message" field.
func SuccessMessageEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldSuccessMessage, v))
}

// SuccessMessageNEQ applies the NEQ predicate on the "success_message" field.
func SuccessMessageNEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldSuccessMessage, v))
}

// SuccessMessageIn applies the In predicate on the "success_message" field.
func SuccessMessageIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldSuccessMessage, vs...))
}

// SuccessMessageNotIn applies the NotIn predicate on the "success_message" field.
func SuccessMessageNotIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldSuccessMessage, vs...))
}

// SuccessMessageGT applies the GT predicate on the "success_message" field.
func SuccessMessageGT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldSuccessMessage, v))
}

// SuccessMessageGTE applies the GTE predicate on the "success_message" field.
func SuccessMessageGTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldSuccessMessage, v))
}

// SuccessMessageLT applies the LT predicate on the "success_message" field.
func SuccessMessageLT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldSuccessMessage, v))
}

// SuccessMessageLTE applies the LTE predicate on the "success_message" field.
func SuccessMessageLTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldSuccessMessage, v))
}

// SuccessMessageContains applies the Contains predicate on the "success_message" field.
func SuccessMessageContains(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContains(FieldSuccessMessage, v))
}

// SuccessMessageHasPrefix applies the HasPrefix predicate on the "success_message" field.
func SuccessMessageHasPrefix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasPrefix(FieldSuccessMessage, v))
}

// SuccessMessageHasSuffix applies the HasSuffix predicate on the "success_message" field.
func SuccessMessageHasSuffix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasSuffix(FieldSuccessMessage, v))
}

// SuccessMessageIsNil applies the IsNil predicate on the "success_message" field.
func SuccessMessageIsNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIsNull(FieldSuccessMessage))
}

// SuccessMessageNotNil applies the NotNil predicate on the "success_message" field.
func SuccessMessageNotNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotNull(FieldSuccessMessage))
}

// SuccessMessageEqualFold applies the EqualFold predicate on the "success_message" field.
func SuccessMessageEqualFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEqualFold(FieldSuccessMessage, v))
}

// SuccessMessageContainsFold applies the ContainsFold predicate on the "success_message" field.
func SuccessMessageContainsFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContainsFold(FieldSuccessMessage, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromoCode {
	return predicate.PromoCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsageRecords applies the HasEdge predicate on the "usage_records" edge.
func HasUsageRecords() predicate.PromoCode {
	return predicate.PromoCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageRecordsTable, UsageRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageRecordsWith applies the HasEdge predicate on the "usage_records" edge with a given conditions (other predicates).
func HasUsageRecordsWith(preds ...predicate.PromoCodeUsage) predicate.PromoCode {
	return predicate.PromoCode(func(s *sql.Selector) {
		step := newUsageRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromoCode) predicate.PromoCode {
	return predicate.PromoCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromoCode) predicate.PromoCode {
	return predicate.PromoCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromoCode) predicate.PromoCode {
	return predicate.PromoCode(sql.NotPredicates(p))
}
