// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthSnapshotDelete is the builder for deleting a GroupHealthSnapshot entity.
type GroupHealthSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *GroupHealthSnapshotMutation
}

// Where appends a list predicates to the GroupHealthSnapshotDelete builder.
func (_d *GroupHealthSnapshotDelete) Where(ps ...predicate.GroupHealthSnapshot) *GroupHealthSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupHealthSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupHealthSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouphealthsnapshot.Table, sqlgraph.NewFieldSpec(grouphealthsnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupHealthSnapshotDeleteOne is the builder for deleting a single GroupHealthSnapshot entity.
type GroupHealthSnapshotDeleteOne struct {
	_d *GroupHealthSnapshotDelete
}

// Where appends a list predicates to the GroupHealthSnapshotDelete builder.
func (_d *GroupHealthSnapshotDeleteOne) Where(ps ...predicate.GroupHealthSnapshot) *GroupHealthSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupHealthSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouphealthsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
