// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthsnapshot"
)

// GroupHealthSnapshot is the model entity for the GroupHealthSnapshot schema.
type GroupHealthSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// BucketTime holds the value of the "bucket_time" field.
	BucketTime time.Time `json:"bucket_time,omitempty"`
	// HealthPercent holds the value of the "health_percent" field.
	HealthPercent int `json:"health_percent,omitempty"`
	// HealthState holds the value of the "health_state" field.
	HealthState  grouphealthsnapshot.HealthState `json:"health_state,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupHealthSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grouphealthsnapshot.FieldID, grouphealthsnapshot.FieldGroupID, grouphealthsnapshot.FieldHealthPercent:
			values[i] = new(sql.NullInt64)
		case grouphealthsnapshot.FieldHealthState:
			values[i] = new(sql.NullString)
		case grouphealthsnapshot.FieldBucketTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupHealthSnapshot fields.
func (_m *GroupHealthSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grouphealthsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case grouphealthsnapshot.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case grouphealthsnapshot.FieldBucketTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_time", values[i])
			} else if value.Valid {
				_m.BucketTime = value.Time
			}
		case grouphealthsnapshot.FieldHealthPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field health_percent", values[i])
			} else if value.Valid {
				_m.HealthPercent = int(value.Int64)
			}
		case grouphealthsnapshot.FieldHealthState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_state", values[i])
			} else if value.Valid {
				_m.HealthState = grouphealthsnapshot.HealthState(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupHealthSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *GroupHealthSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupHealthSnapshot.
// Note that you need to call GroupHealthSnapshot.Unwrap() before calling this method if this GroupHealthSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupHealthSnapshot) Update() *GroupHealthSnapshotUpdateOne {
	return NewGroupHealthSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupHealthSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupHealthSnapshot) Unwrap() *GroupHealthSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupHealthSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupHealthSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("GroupHealthSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("bucket_time=")
	builder.WriteString(_m.BucketTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("health_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthPercent))
	builder.WriteString(", ")
	builder.WriteString("health_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthState))
	builder.WriteByte(')')
	return builder.String()
}

// GroupHealthSnapshots is a parsable slice of GroupHealthSnapshot.
type GroupHealthSnapshots []*GroupHealthSnapshot
