// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthSnapshotUpdate is the builder for updating GroupHealthSnapshot entities.
type GroupHealthSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *GroupHealthSnapshotMutation
}

// Where appends a list predicates to the GroupHealthSnapshotUpdate builder.
func (_u *GroupHealthSnapshotUpdate) Where(ps ...predicate.GroupHealthSnapshot) *GroupHealthSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthSnapshotUpdate) SetGroupID(v int64) *GroupHealthSnapshotUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdate) SetNillableGroupID(v *int64) *GroupHealthSnapshotUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupHealthSnapshotUpdate) AddGroupID(v int64) *GroupHealthSnapshotUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBucketTime sets the "bucket_time" field.
func (_u *GroupHealthSnapshotUpdate) SetBucketTime(v time.Time) *GroupHealthSnapshotUpdate {
	_u.mutation.SetBucketTime(v)
	return _u
}

// SetNillableBucketTime sets the "bucket_time" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdate) SetNillableBucketTime(v *time.Time) *GroupHealthSnapshotUpdate {
	if v != nil {
		_u.SetBucketTime(*v)
	}
	return _u
}

// SetHealthPercent sets the "health_percent" field.
func (_u *GroupHealthSnapshotUpdate) SetHealthPercent(v int) *GroupHealthSnapshotUpdate {
	_u.mutation.ResetHealthPercent()
	_u.mutation.SetHealthPercent(v)
	return _u
}

// SetNillableHealthPercent sets the "health_percent" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdate) SetNillableHealthPercent(v *int) *GroupHealthSnapshotUpdate {
	if v != nil {
		_u.SetHealthPercent(*v)
	}
	return _u
}

// AddHealthPercent adds value to the "health_percent" field.
func (_u *GroupHealthSnapshotUpdate) AddHealthPercent(v int) *GroupHealthSnapshotUpdate {
	_u.mutation.AddHealthPercent(v)
	return _u
}

// SetHealthState sets the "health_state" field.
func (_u *GroupHealthSnapshotUpdate) SetHealthState(v grouphealthsnapshot.HealthState) *GroupHealthSnapshotUpdate {
	_u.mutation.SetHealthState(v)
	return _u
}

// SetNillableHealthState sets the "health_state" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdate) SetNillableHealthState(v *grouphealthsnapshot.HealthState) *GroupHealthSnapshotUpdate {
	if v != nil {
		_u.SetHealthState(*v)
	}
	return _u
}

// Mutation returns the GroupHealthSnapshotMutation object of the builder.
func (_u *GroupHealthSnapshotUpdate) Mutation() *GroupHealthSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupHealthSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupHealthSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthSnapshotUpdate) check() error {
	if v, ok := _u.mutation.HealthPercent(); ok {
		if err := grouphealthsnapshot.HealthPercentValidator(v); err != nil {
			return &ValidationError{Name: "health_percent", err: fmt.Errorf(`ent: validator failed for field "GroupHealthSnapshot.health_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthState(); ok {
		if err := grouphealthsnapshot.HealthStateValidator(v); err != nil {
			return &ValidationError{Name: "health_state", err: fmt.Errorf(`ent: validator failed for field "GroupHealthSnapshot.health_state": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupHealthSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthsnapshot.Table, grouphealthsnapshot.Columns, sqlgraph.NewFieldSpec(grouphealthsnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grouphealthsnapshot.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grouphealthsnapshot.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BucketTime(); ok {
		_spec.SetField(grouphealthsnapshot.FieldBucketTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HealthPercent(); ok {
		_spec.SetField(grouphealthsnapshot.FieldHealthPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthPercent(); ok {
		_spec.AddField(grouphealthsnapshot.FieldHealthPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HealthState(); ok {
		_spec.SetField(grouphealthsnapshot.FieldHealthState, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupHealthSnapshotUpdateOne is the builder for updating a single GroupHealthSnapshot entity.
type GroupHealthSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupHealthSnapshotMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthSnapshotUpdateOne) SetGroupID(v int64) *GroupHealthSnapshotUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdateOne) SetNillableGroupID(v *int64) *GroupHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupHealthSnapshotUpdateOne) AddGroupID(v int64) *GroupHealthSnapshotUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBucketTime sets the "bucket_time" field.
func (_u *GroupHealthSnapshotUpdateOne) SetBucketTime(v time.Time) *GroupHealthSnapshotUpdateOne {
	_u.mutation.SetBucketTime(v)
	return _u
}

// SetNillableBucketTime sets the "bucket_time" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdateOne) SetNillableBucketTime(v *time.Time) *GroupHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetBucketTime(*v)
	}
	return _u
}

// SetHealthPercent sets the "health_percent" field.
func (_u *GroupHealthSnapshotUpdateOne) SetHealthPercent(v int) *GroupHealthSnapshotUpdateOne {
	_u.mutation.ResetHealthPercent()
	_u.mutation.SetHealthPercent(v)
	return _u
}

// SetNillableHealthPercent sets the "health_percent" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdateOne) SetNillableHealthPercent(v *int) *GroupHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetHealthPercent(*v)
	}
	return _u
}

// AddHealthPercent adds value to the "health_percent" field.
func (_u *GroupHealthSnapshotUpdateOne) AddHealthPercent(v int) *GroupHealthSnapshotUpdateOne {
	_u.mutation.AddHealthPercent(v)
	return _u
}

// SetHealthState sets the "health_state" field.
func (_u *GroupHealthSnapshotUpdateOne) SetHealthState(v grouphealthsnapshot.HealthState) *GroupHealthSnapshotUpdateOne {
	_u.mutation.SetHealthState(v)
	return _u
}

// SetNillableHealthState sets the "health_state" field if the given value is not nil.
func (_u *GroupHealthSnapshotUpdateOne) SetNillableHealthState(v *grouphealthsnapshot.HealthState) *GroupHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetHealthState(*v)
	}
	return _u
}

// Mutation returns the GroupHealthSnapshotMutation object of the builder.
func (_u *GroupHealthSnapshotUpdateOne) Mutation() *GroupHealthSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupHealthSnapshotUpdate builder.
func (_u *GroupHealthSnapshotUpdateOne) Where(ps ...predicate.GroupHealthSnapshot) *GroupHealthSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupHealthSnapshotUpdateOne) Select(field string, fields ...string) *GroupHealthSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupHealthSnapshot entity.
func (_u *GroupHealthSnapshotUpdateOne) Save(ctx context.Context) (*GroupHealthSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthSnapshotUpdateOne) SaveX(ctx context.Context) *GroupHealthSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupHealthSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.HealthPercent(); ok {
		if err := grouphealthsnapshot.HealthPercentValidator(v); err != nil {
			return &ValidationError{Name: "health_percent", err: fmt.Errorf(`ent: validator failed for field "GroupHealthSnapshot.health_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthState(); ok {
		if err := grouphealthsnapshot.HealthStateValidator(v); err != nil {
			return &ValidationError{Name: "health_state", err: fmt.Errorf(`ent: validator failed for field "GroupHealthSnapshot.health_state": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupHealthSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *GroupHealthSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthsnapshot.Table, grouphealthsnapshot.Columns, sqlgraph.NewFieldSpec(grouphealthsnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupHealthSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grouphealthsnapshot.FieldID)
		for _, f := range fields {
			if !grouphealthsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grouphealthsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grouphealthsnapshot.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grouphealthsnapshot.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BucketTime(); ok {
		_spec.SetField(grouphealthsnapshot.FieldBucketTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HealthPercent(); ok {
		_spec.SetField(grouphealthsnapshot.FieldHealthPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthPercent(); ok {
		_spec.AddField(grouphealthsnapshot.FieldHealthPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HealthState(); ok {
		_spec.SetField(grouphealthsnapshot.FieldHealthState, field.TypeEnum, value)
	}
	_node = &GroupHealthSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
