// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/inviterelationshipevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InviteRelationshipEventUpdate is the builder for updating InviteRelationshipEvent entities.
type InviteRelationshipEventUpdate struct {
	config
	hooks    []Hook
	mutation *InviteRelationshipEventMutation
}

// Where appends a list predicates to the InviteRelationshipEventUpdate builder.
func (_u *InviteRelationshipEventUpdate) Where(ps ...predicate.InviteRelationshipEvent) *InviteRelationshipEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *InviteRelationshipEventUpdate) SetInviteeUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.ResetInviteeUserID()
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableInviteeUserID(v *int64) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// AddInviteeUserID adds value to the "invitee_user_id" field.
func (_u *InviteRelationshipEventUpdate) AddInviteeUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.AddInviteeUserID(v)
	return _u
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) SetPreviousInviterUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.ResetPreviousInviterUserID()
	_u.mutation.SetPreviousInviterUserID(v)
	return _u
}

// SetNillablePreviousInviterUserID sets the "previous_inviter_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillablePreviousInviterUserID(v *int64) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetPreviousInviterUserID(*v)
	}
	return _u
}

// AddPreviousInviterUserID adds value to the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) AddPreviousInviterUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.AddPreviousInviterUserID(v)
	return _u
}

// ClearPreviousInviterUserID clears the value of the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) ClearPreviousInviterUserID() *InviteRelationshipEventUpdate {
	_u.mutation.ClearPreviousInviterUserID()
	return _u
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) SetNewInviterUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.ResetNewInviterUserID()
	_u.mutation.SetNewInviterUserID(v)
	return _u
}

// SetNillableNewInviterUserID sets the "new_inviter_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableNewInviterUserID(v *int64) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetNewInviterUserID(*v)
	}
	return _u
}

// AddNewInviterUserID adds value to the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) AddNewInviterUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.AddNewInviterUserID(v)
	return _u
}

// ClearNewInviterUserID clears the value of the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdate) ClearNewInviterUserID() *InviteRelationshipEventUpdate {
	_u.mutation.ClearNewInviterUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *InviteRelationshipEventUpdate) SetEventType(v string) *InviteRelationshipEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableEventType(v *string) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *InviteRelationshipEventUpdate) SetEffectiveAt(v time.Time) *InviteRelationshipEventUpdate {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableEffectiveAt(v *time.Time) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdate) SetOperatorUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableOperatorUserID(v *int64) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdate) AddOperatorUserID(v int64) *InviteRelationshipEventUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdate) ClearOperatorUserID() *InviteRelationshipEventUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *InviteRelationshipEventUpdate) SetReason(v string) *InviteRelationshipEventUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdate) SetNillableReason(v *string) *InviteRelationshipEventUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *InviteRelationshipEventUpdate) ClearReason() *InviteRelationshipEventUpdate {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the InviteRelationshipEventMutation object of the builder.
func (_u *InviteRelationshipEventUpdate) Mutation() *InviteRelationshipEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteRelationshipEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteRelationshipEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteRelationshipEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteRelationshipEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteRelationshipEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := inviterelationshipevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "InviteRelationshipEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteRelationshipEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inviterelationshipevent.Table, inviterelationshipevent.Columns, sqlgraph.NewFieldSpec(inviterelationshipevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviteeUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreviousInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPreviousInviterUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64, value)
	}
	if _u.mutation.PreviousInviterUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NewInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNewInviterUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64, value)
	}
	if _u.mutation.NewInviterUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(inviterelationshipevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(inviterelationshipevent.FieldEffectiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(inviterelationshipevent.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(inviterelationshipevent.FieldReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inviterelationshipevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteRelationshipEventUpdateOne is the builder for updating a single InviteRelationshipEvent entity.
type InviteRelationshipEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteRelationshipEventMutation
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) SetInviteeUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.ResetInviteeUserID()
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableInviteeUserID(v *int64) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// AddInviteeUserID adds value to the "invitee_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) AddInviteeUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.AddInviteeUserID(v)
	return _u
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) SetPreviousInviterUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.ResetPreviousInviterUserID()
	_u.mutation.SetPreviousInviterUserID(v)
	return _u
}

// SetNillablePreviousInviterUserID sets the "previous_inviter_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillablePreviousInviterUserID(v *int64) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetPreviousInviterUserID(*v)
	}
	return _u
}

// AddPreviousInviterUserID adds value to the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) AddPreviousInviterUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.AddPreviousInviterUserID(v)
	return _u
}

// ClearPreviousInviterUserID clears the value of the "previous_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) ClearPreviousInviterUserID() *InviteRelationshipEventUpdateOne {
	_u.mutation.ClearPreviousInviterUserID()
	return _u
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) SetNewInviterUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.ResetNewInviterUserID()
	_u.mutation.SetNewInviterUserID(v)
	return _u
}

// SetNillableNewInviterUserID sets the "new_inviter_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableNewInviterUserID(v *int64) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetNewInviterUserID(*v)
	}
	return _u
}

// AddNewInviterUserID adds value to the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) AddNewInviterUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.AddNewInviterUserID(v)
	return _u
}

// ClearNewInviterUserID clears the value of the "new_inviter_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) ClearNewInviterUserID() *InviteRelationshipEventUpdateOne {
	_u.mutation.ClearNewInviterUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *InviteRelationshipEventUpdateOne) SetEventType(v string) *InviteRelationshipEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableEventType(v *string) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *InviteRelationshipEventUpdateOne) SetEffectiveAt(v time.Time) *InviteRelationshipEventUpdateOne {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableEffectiveAt(v *time.Time) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) SetOperatorUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableOperatorUserID(v *int64) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) AddOperatorUserID(v int64) *InviteRelationshipEventUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *InviteRelationshipEventUpdateOne) ClearOperatorUserID() *InviteRelationshipEventUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *InviteRelationshipEventUpdateOne) SetReason(v string) *InviteRelationshipEventUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *InviteRelationshipEventUpdateOne) SetNillableReason(v *string) *InviteRelationshipEventUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *InviteRelationshipEventUpdateOne) ClearReason() *InviteRelationshipEventUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the InviteRelationshipEventMutation object of the builder.
func (_u *InviteRelationshipEventUpdateOne) Mutation() *InviteRelationshipEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the InviteRelationshipEventUpdate builder.
func (_u *InviteRelationshipEventUpdateOne) Where(ps ...predicate.InviteRelationshipEvent) *InviteRelationshipEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteRelationshipEventUpdateOne) Select(field string, fields ...string) *InviteRelationshipEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteRelationshipEvent entity.
func (_u *InviteRelationshipEventUpdateOne) Save(ctx context.Context) (*InviteRelationshipEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteRelationshipEventUpdateOne) SaveX(ctx context.Context) *InviteRelationshipEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteRelationshipEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteRelationshipEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteRelationshipEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := inviterelationshipevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "InviteRelationshipEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteRelationshipEventUpdateOne) sqlSave(ctx context.Context) (_node *InviteRelationshipEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inviterelationshipevent.Table, inviterelationshipevent.Columns, sqlgraph.NewFieldSpec(inviterelationshipevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteRelationshipEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inviterelationshipevent.FieldID)
		for _, f := range fields {
			if !inviterelationshipevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inviterelationshipevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviteeUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreviousInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPreviousInviterUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64, value)
	}
	if _u.mutation.PreviousInviterUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NewInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNewInviterUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64, value)
	}
	if _u.mutation.NewInviterUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(inviterelationshipevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(inviterelationshipevent.FieldEffectiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(inviterelationshipevent.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(inviterelationshipevent.FieldReason, field.TypeString)
	}
	_node = &InviteRelationshipEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inviterelationshipevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
