// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/inviterelationshipevent"
)

// InviteRelationshipEventCreate is the builder for creating a InviteRelationshipEvent entity.
type InviteRelationshipEventCreate struct {
	config
	mutation *InviteRelationshipEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_c *InviteRelationshipEventCreate) SetInviteeUserID(v int64) *InviteRelationshipEventCreate {
	_c.mutation.SetInviteeUserID(v)
	return _c
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (_c *InviteRelationshipEventCreate) SetPreviousInviterUserID(v int64) *InviteRelationshipEventCreate {
	_c.mutation.SetPreviousInviterUserID(v)
	return _c
}

// SetNillablePreviousInviterUserID sets the "previous_inviter_user_id" field if the given value is not nil.
func (_c *InviteRelationshipEventCreate) SetNillablePreviousInviterUserID(v *int64) *InviteRelationshipEventCreate {
	if v != nil {
		_c.SetPreviousInviterUserID(*v)
	}
	return _c
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (_c *InviteRelationshipEventCreate) SetNewInviterUserID(v int64) *InviteRelationshipEventCreate {
	_c.mutation.SetNewInviterUserID(v)
	return _c
}

// SetNillableNewInviterUserID sets the "new_inviter_user_id" field if the given value is not nil.
func (_c *InviteRelationshipEventCreate) SetNillableNewInviterUserID(v *int64) *InviteRelationshipEventCreate {
	if v != nil {
		_c.SetNewInviterUserID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *InviteRelationshipEventCreate) SetEventType(v string) *InviteRelationshipEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetEffectiveAt sets the "effective_at" field.
func (_c *InviteRelationshipEventCreate) SetEffectiveAt(v time.Time) *InviteRelationshipEventCreate {
	_c.mutation.SetEffectiveAt(v)
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *InviteRelationshipEventCreate) SetOperatorUserID(v int64) *InviteRelationshipEventCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *InviteRelationshipEventCreate) SetNillableOperatorUserID(v *int64) *InviteRelationshipEventCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *InviteRelationshipEventCreate) SetReason(v string) *InviteRelationshipEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *InviteRelationshipEventCreate) SetNillableReason(v *string) *InviteRelationshipEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteRelationshipEventCreate) SetCreatedAt(v time.Time) *InviteRelationshipEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteRelationshipEventCreate) SetNillableCreatedAt(v *time.Time) *InviteRelationshipEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the InviteRelationshipEventMutation object of the builder.
func (_c *InviteRelationshipEventCreate) Mutation() *InviteRelationshipEventMutation {
	return _c.mutation
}

// Save creates the InviteRelationshipEvent in the database.
func (_c *InviteRelationshipEventCreate) Save(ctx context.Context) (*InviteRelationshipEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteRelationshipEventCreate) SaveX(ctx context.Context) *InviteRelationshipEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteRelationshipEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteRelationshipEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteRelationshipEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inviterelationshipevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteRelationshipEventCreate) check() error {
	if _, ok := _c.mutation.InviteeUserID(); !ok {
		return &ValidationError{Name: "invitee_user_id", err: errors.New(`ent: missing required field "InviteRelationshipEvent.invitee_user_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "InviteRelationshipEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := inviterelationshipevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "InviteRelationshipEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EffectiveAt(); !ok {
		return &ValidationError{Name: "effective_at", err: errors.New(`ent: missing required field "InviteRelationshipEvent.effective_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteRelationshipEvent.created_at"`)}
	}
	return nil
}

func (_c *InviteRelationshipEventCreate) sqlSave(ctx context.Context) (*InviteRelationshipEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteRelationshipEventCreate) createSpec() (*InviteRelationshipEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteRelationshipEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inviterelationshipevent.Table, sqlgraph.NewFieldSpec(inviterelationshipevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviteeUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldInviteeUserID, field.TypeInt64, value)
		_node.InviteeUserID = value
	}
	if value, ok := _c.mutation.PreviousInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldPreviousInviterUserID, field.TypeInt64, value)
		_node.PreviousInviterUserID = &value
	}
	if value, ok := _c.mutation.NewInviterUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldNewInviterUserID, field.TypeInt64, value)
		_node.NewInviterUserID = &value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(inviterelationshipevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EffectiveAt(); ok {
		_spec.SetField(inviterelationshipevent.FieldEffectiveAt, field.TypeTime, value)
		_node.EffectiveAt = value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(inviterelationshipevent.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(inviterelationshipevent.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inviterelationshipevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteRelationshipEvent.Create().
//		SetInviteeUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteRelationshipEventUpsert) {
//			SetInviteeUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteRelationshipEventCreate) OnConflict(opts ...sql.ConflictOption) *InviteRelationshipEventUpsertOne {
	_c.conflict = opts
	return &InviteRelationshipEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteRelationshipEventCreate) OnConflictColumns(columns ...string) *InviteRelationshipEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteRelationshipEventUpsertOne{
		create: _c,
	}
}

type (
	// InviteRelationshipEventUpsertOne is the builder for "upsert"-ing
	//  one InviteRelationshipEvent node.
	InviteRelationshipEventUpsertOne struct {
		create *InviteRelationshipEventCreate
	}

	// InviteRelationshipEventUpsert is the "OnConflict" setter.
	InviteRelationshipEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsert) SetInviteeUserID(v int64) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldInviteeUserID, v)
	return u
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateInviteeUserID() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldInviteeUserID)
	return u
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsert) AddInviteeUserID(v int64) *InviteRelationshipEventUpsert {
	u.Add(inviterelationshipevent.FieldInviteeUserID, v)
	return u
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) SetPreviousInviterUserID(v int64) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldPreviousInviterUserID, v)
	return u
}

// UpdatePreviousInviterUserID sets the "previous_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdatePreviousInviterUserID() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldPreviousInviterUserID)
	return u
}

// AddPreviousInviterUserID adds v to the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) AddPreviousInviterUserID(v int64) *InviteRelationshipEventUpsert {
	u.Add(inviterelationshipevent.FieldPreviousInviterUserID, v)
	return u
}

// ClearPreviousInviterUserID clears the value of the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) ClearPreviousInviterUserID() *InviteRelationshipEventUpsert {
	u.SetNull(inviterelationshipevent.FieldPreviousInviterUserID)
	return u
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) SetNewInviterUserID(v int64) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldNewInviterUserID, v)
	return u
}

// UpdateNewInviterUserID sets the "new_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateNewInviterUserID() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldNewInviterUserID)
	return u
}

// AddNewInviterUserID adds v to the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) AddNewInviterUserID(v int64) *InviteRelationshipEventUpsert {
	u.Add(inviterelationshipevent.FieldNewInviterUserID, v)
	return u
}

// ClearNewInviterUserID clears the value of the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsert) ClearNewInviterUserID() *InviteRelationshipEventUpsert {
	u.SetNull(inviterelationshipevent.FieldNewInviterUserID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *InviteRelationshipEventUpsert) SetEventType(v string) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateEventType() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldEventType)
	return u
}

// SetEffectiveAt sets the "effective_at" field.
func (u *InviteRelationshipEventUpsert) SetEffectiveAt(v time.Time) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldEffectiveAt, v)
	return u
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateEffectiveAt() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldEffectiveAt)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *InviteRelationshipEventUpsert) SetOperatorUserID(v int64) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateOperatorUserID() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *InviteRelationshipEventUpsert) AddOperatorUserID(v int64) *InviteRelationshipEventUpsert {
	u.Add(inviterelationshipevent.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *InviteRelationshipEventUpsert) ClearOperatorUserID() *InviteRelationshipEventUpsert {
	u.SetNull(inviterelationshipevent.FieldOperatorUserID)
	return u
}

// SetReason sets the "reason" field.
func (u *InviteRelationshipEventUpsert) SetReason(v string) *InviteRelationshipEventUpsert {
	u.Set(inviterelationshipevent.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsert) UpdateReason() *InviteRelationshipEventUpsert {
	u.SetExcluded(inviterelationshipevent.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRelationshipEventUpsert) ClearReason() *InviteRelationshipEventUpsert {
	u.SetNull(inviterelationshipevent.FieldReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteRelationshipEventUpsertOne) UpdateNewValues() *InviteRelationshipEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(inviterelationshipevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteRelationshipEventUpsertOne) Ignore() *InviteRelationshipEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteRelationshipEventUpsertOne) DoNothing() *InviteRelationshipEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteRelationshipEventCreate.OnConflict
// documentation for more info.
func (u *InviteRelationshipEventUpsertOne) Update(set func(*InviteRelationshipEventUpsert)) *InviteRelationshipEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteRelationshipEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsertOne) SetInviteeUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsertOne) AddInviteeUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateInviteeUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) SetPreviousInviterUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetPreviousInviterUserID(v)
	})
}

// AddPreviousInviterUserID adds v to the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) AddPreviousInviterUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddPreviousInviterUserID(v)
	})
}

// UpdatePreviousInviterUserID sets the "previous_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdatePreviousInviterUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdatePreviousInviterUserID()
	})
}

// ClearPreviousInviterUserID clears the value of the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) ClearPreviousInviterUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearPreviousInviterUserID()
	})
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) SetNewInviterUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetNewInviterUserID(v)
	})
}

// AddNewInviterUserID adds v to the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) AddNewInviterUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddNewInviterUserID(v)
	})
}

// UpdateNewInviterUserID sets the "new_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateNewInviterUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateNewInviterUserID()
	})
}

// ClearNewInviterUserID clears the value of the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertOne) ClearNewInviterUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearNewInviterUserID()
	})
}

// SetEventType sets the "event_type" field.
func (u *InviteRelationshipEventUpsertOne) SetEventType(v string) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateEventType() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateEventType()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *InviteRelationshipEventUpsertOne) SetEffectiveAt(v time.Time) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateEffectiveAt() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateEffectiveAt()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertOne) SetOperatorUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertOne) AddOperatorUserID(v int64) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateOperatorUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertOne) ClearOperatorUserID() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetReason sets the "reason" field.
func (u *InviteRelationshipEventUpsertOne) SetReason(v string) *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertOne) UpdateReason() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRelationshipEventUpsertOne) ClearReason() *InviteRelationshipEventUpsertOne {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *InviteRelationshipEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteRelationshipEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteRelationshipEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteRelationshipEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteRelationshipEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteRelationshipEventCreateBulk is the builder for creating many InviteRelationshipEvent entities in bulk.
type InviteRelationshipEventCreateBulk struct {
	config
	err      error
	builders []*InviteRelationshipEventCreate
	conflict []sql.ConflictOption
}

// Save creates the InviteRelationshipEvent entities in the database.
func (_c *InviteRelationshipEventCreateBulk) Save(ctx context.Context) ([]*InviteRelationshipEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteRelationshipEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteRelationshipEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteRelationshipEventCreateBulk) SaveX(ctx context.Context) []*InviteRelationshipEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteRelationshipEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteRelationshipEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteRelationshipEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteRelationshipEventUpsert) {
//			SetInviteeUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteRelationshipEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteRelationshipEventUpsertBulk {
	_c.conflict = opts
	return &InviteRelationshipEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteRelationshipEventCreateBulk) OnConflictColumns(columns ...string) *InviteRelationshipEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteRelationshipEventUpsertBulk{
		create: _c,
	}
}

// InviteRelationshipEventUpsertBulk is the builder for "upsert"-ing
// a bulk of InviteRelationshipEvent nodes.
type InviteRelationshipEventUpsertBulk struct {
	create *InviteRelationshipEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteRelationshipEventUpsertBulk) UpdateNewValues() *InviteRelationshipEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(inviterelationshipevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteRelationshipEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteRelationshipEventUpsertBulk) Ignore() *InviteRelationshipEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteRelationshipEventUpsertBulk) DoNothing() *InviteRelationshipEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteRelationshipEventCreateBulk.OnConflict
// documentation for more info.
func (u *InviteRelationshipEventUpsertBulk) Update(set func(*InviteRelationshipEventUpsert)) *InviteRelationshipEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteRelationshipEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) SetInviteeUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) AddInviteeUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateInviteeUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetPreviousInviterUserID sets the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) SetPreviousInviterUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetPreviousInviterUserID(v)
	})
}

// AddPreviousInviterUserID adds v to the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) AddPreviousInviterUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddPreviousInviterUserID(v)
	})
}

// UpdatePreviousInviterUserID sets the "previous_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdatePreviousInviterUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdatePreviousInviterUserID()
	})
}

// ClearPreviousInviterUserID clears the value of the "previous_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) ClearPreviousInviterUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearPreviousInviterUserID()
	})
}

// SetNewInviterUserID sets the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) SetNewInviterUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetNewInviterUserID(v)
	})
}

// AddNewInviterUserID adds v to the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) AddNewInviterUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddNewInviterUserID(v)
	})
}

// UpdateNewInviterUserID sets the "new_inviter_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateNewInviterUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateNewInviterUserID()
	})
}

// ClearNewInviterUserID clears the value of the "new_inviter_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) ClearNewInviterUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearNewInviterUserID()
	})
}

// SetEventType sets the "event_type" field.
func (u *InviteRelationshipEventUpsertBulk) SetEventType(v string) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateEventType() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateEventType()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *InviteRelationshipEventUpsertBulk) SetEffectiveAt(v time.Time) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateEffectiveAt() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateEffectiveAt()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) SetOperatorUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) AddOperatorUserID(v int64) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateOperatorUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *InviteRelationshipEventUpsertBulk) ClearOperatorUserID() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetReason sets the "reason" field.
func (u *InviteRelationshipEventUpsertBulk) SetReason(v string) *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRelationshipEventUpsertBulk) UpdateReason() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRelationshipEventUpsertBulk) ClearReason() *InviteRelationshipEventUpsertBulk {
	return u.Update(func(s *InviteRelationshipEventUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *InviteRelationshipEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteRelationshipEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteRelationshipEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteRelationshipEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
