// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/inviteadminaction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InviteAdminActionDelete is the builder for deleting a InviteAdminAction entity.
type InviteAdminActionDelete struct {
	config
	hooks    []Hook
	mutation *InviteAdminActionMutation
}

// Where appends a list predicates to the InviteAdminActionDelete builder.
func (_d *InviteAdminActionDelete) Where(ps ...predicate.InviteAdminAction) *InviteAdminActionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InviteAdminActionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InviteAdminActionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InviteAdminActionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(inviteadminaction.Table, sqlgraph.NewFieldSpec(inviteadminaction.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InviteAdminActionDeleteOne is the builder for deleting a single InviteAdminAction entity.
type InviteAdminActionDeleteOne struct {
	_d *InviteAdminActionDelete
}

// Where appends a list predicates to the InviteAdminActionDelete builder.
func (_d *InviteAdminActionDeleteOne) Where(ps ...predicate.InviteAdminAction) *InviteAdminActionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InviteAdminActionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{inviteadminaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InviteAdminActionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
