// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/inviterelationshipevent"
)

// InviteRelationshipEvent is the model entity for the InviteRelationshipEvent schema.
type InviteRelationshipEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// PreviousInviterUserID holds the value of the "previous_inviter_user_id" field.
	PreviousInviterUserID *int64 `json:"previous_inviter_user_id,omitempty"`
	// NewInviterUserID holds the value of the "new_inviter_user_id" field.
	NewInviterUserID *int64 `json:"new_inviter_user_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// EffectiveAt holds the value of the "effective_at" field.
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID *int64 `json:"operator_user_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteRelationshipEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inviterelationshipevent.FieldID, inviterelationshipevent.FieldInviteeUserID, inviterelationshipevent.FieldPreviousInviterUserID, inviterelationshipevent.FieldNewInviterUserID, inviterelationshipevent.FieldOperatorUserID:
			values[i] = new(sql.NullInt64)
		case inviterelationshipevent.FieldEventType, inviterelationshipevent.FieldReason:
			values[i] = new(sql.NullString)
		case inviterelationshipevent.FieldEffectiveAt, inviterelationshipevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteRelationshipEvent fields.
func (_m *InviteRelationshipEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inviterelationshipevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case inviterelationshipevent.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case inviterelationshipevent.FieldPreviousInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field previous_inviter_user_id", values[i])
			} else if value.Valid {
				_m.PreviousInviterUserID = new(int64)
				*_m.PreviousInviterUserID = value.Int64
			}
		case inviterelationshipevent.FieldNewInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_inviter_user_id", values[i])
			} else if value.Valid {
				_m.NewInviterUserID = new(int64)
				*_m.NewInviterUserID = value.Int64
			}
		case inviterelationshipevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case inviterelationshipevent.FieldEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_at", values[i])
			} else if value.Valid {
				_m.EffectiveAt = value.Time
			}
		case inviterelationshipevent.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = new(int64)
				*_m.OperatorUserID = value.Int64
			}
		case inviterelationshipevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case inviterelationshipevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteRelationshipEvent.
// This includes values selected through modifiers, order, etc.
func (_m *InviteRelationshipEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InviteRelationshipEvent.
// Note that you need to call InviteRelationshipEvent.Unwrap() before calling this method if this InviteRelationshipEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteRelationshipEvent) Update() *InviteRelationshipEventUpdateOne {
	return NewInviteRelationshipEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteRelationshipEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteRelationshipEvent) Unwrap() *InviteRelationshipEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteRelationshipEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteRelationshipEvent) String() string {
	var builder strings.Builder
	builder.WriteString("InviteRelationshipEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	if v := _m.PreviousInviterUserID; v != nil {
		builder.WriteString("previous_inviter_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NewInviterUserID; v != nil {
		builder.WriteString("new_inviter_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("effective_at=")
	builder.WriteString(_m.EffectiveAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OperatorUserID; v != nil {
		builder.WriteString("operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteRelationshipEvents is a parsable slice of InviteRelationshipEvent.
type InviteRelationshipEvents []*InviteRelationshipEvent
