// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/inviterewardrecord"
)

// InviteRewardRecord is the model entity for the InviteRewardRecord schema.
type InviteRewardRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviterUserID holds the value of the "inviter_user_id" field.
	InviterUserID int64 `json:"inviter_user_id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// TriggerRedeemCodeID holds the value of the "trigger_redeem_code_id" field.
	TriggerRedeemCodeID *int64 `json:"trigger_redeem_code_id,omitempty"`
	// TriggerRedeemCodeValue holds the value of the "trigger_redeem_code_value" field.
	TriggerRedeemCodeValue float64 `json:"trigger_redeem_code_value,omitempty"`
	// RewardTargetUserID holds the value of the "reward_target_user_id" field.
	RewardTargetUserID int64 `json:"reward_target_user_id,omitempty"`
	// RewardRole holds the value of the "reward_role" field.
	RewardRole string `json:"reward_role,omitempty"`
	// RewardType holds the value of the "reward_type" field.
	RewardType string `json:"reward_type,omitempty"`
	// RewardRate holds the value of the "reward_rate" field.
	RewardRate *float64 `json:"reward_rate,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// AdminActionID holds the value of the "admin_action_id" field.
	AdminActionID *int64 `json:"admin_action_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteRewardRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inviterewardrecord.FieldTriggerRedeemCodeValue, inviterewardrecord.FieldRewardRate, inviterewardrecord.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case inviterewardrecord.FieldID, inviterewardrecord.FieldInviterUserID, inviterewardrecord.FieldInviteeUserID, inviterewardrecord.FieldTriggerRedeemCodeID, inviterewardrecord.FieldRewardTargetUserID, inviterewardrecord.FieldAdminActionID:
			values[i] = new(sql.NullInt64)
		case inviterewardrecord.FieldRewardRole, inviterewardrecord.FieldRewardType, inviterewardrecord.FieldStatus, inviterewardrecord.FieldNotes:
			values[i] = new(sql.NullString)
		case inviterewardrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteRewardRecord fields.
func (_m *InviteRewardRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inviterewardrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case inviterewardrecord.FieldInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_user_id", values[i])
			} else if value.Valid {
				_m.InviterUserID = value.Int64
			}
		case inviterewardrecord.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case inviterewardrecord.FieldTriggerRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_redeem_code_id", values[i])
			} else if value.Valid {
				_m.TriggerRedeemCodeID = new(int64)
				*_m.TriggerRedeemCodeID = value.Int64
			}
		case inviterewardrecord.FieldTriggerRedeemCodeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_redeem_code_value", values[i])
			} else if value.Valid {
				_m.TriggerRedeemCodeValue = value.Float64
			}
		case inviterewardrecord.FieldRewardTargetUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_target_user_id", values[i])
			} else if value.Valid {
				_m.RewardTargetUserID = value.Int64
			}
		case inviterewardrecord.FieldRewardRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_role", values[i])
			} else if value.Valid {
				_m.RewardRole = value.String
			}
		case inviterewardrecord.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = value.String
			}
		case inviterewardrecord.FieldRewardRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_rate", values[i])
			} else if value.Valid {
				_m.RewardRate = new(float64)
				*_m.RewardRate = value.Float64
			}
		case inviterewardrecord.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case inviterewardrecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case inviterewardrecord.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case inviterewardrecord.FieldAdminActionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_action_id", values[i])
			} else if value.Valid {
				_m.AdminActionID = new(int64)
				*_m.AdminActionID = value.Int64
			}
		case inviterewardrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteRewardRecord.
// This includes values selected through modifiers, order, etc.
func (_m *InviteRewardRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InviteRewardRecord.
// Note that you need to call InviteRewardRecord.Unwrap() before calling this method if this InviteRewardRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteRewardRecord) Update() *InviteRewardRecordUpdateOne {
	return NewInviteRewardRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteRewardRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteRewardRecord) Unwrap() *InviteRewardRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteRewardRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteRewardRecord) String() string {
	var builder strings.Builder
	builder.WriteString("InviteRewardRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterUserID))
	builder.WriteString(", ")
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	if v := _m.TriggerRedeemCodeID; v != nil {
		builder.WriteString("trigger_redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("trigger_redeem_code_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerRedeemCodeValue))
	builder.WriteString(", ")
	builder.WriteString("reward_target_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardTargetUserID))
	builder.WriteString(", ")
	builder.WriteString("reward_role=")
	builder.WriteString(_m.RewardRole)
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(_m.RewardType)
	builder.WriteString(", ")
	if v := _m.RewardRate; v != nil {
		builder.WriteString("reward_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AdminActionID; v != nil {
		builder.WriteString("admin_action_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteRewardRecords is a parsable slice of InviteRewardRecord.
type InviteRewardRecords []*InviteRewardRecord
