// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/productsubscriptionmigrationsource"
)

// ProductSubscriptionMigrationSourceDelete is the builder for deleting a ProductSubscriptionMigrationSource entity.
type ProductSubscriptionMigrationSourceDelete struct {
	config
	hooks    []Hook
	mutation *ProductSubscriptionMigrationSourceMutation
}

// Where appends a list predicates to the ProductSubscriptionMigrationSourceDelete builder.
func (_d *ProductSubscriptionMigrationSourceDelete) Where(ps ...predicate.ProductSubscriptionMigrationSource) *ProductSubscriptionMigrationSourceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProductSubscriptionMigrationSourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProductSubscriptionMigrationSourceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProductSubscriptionMigrationSourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productsubscriptionmigrationsource.Table, sqlgraph.NewFieldSpec(productsubscriptionmigrationsource.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProductSubscriptionMigrationSourceDeleteOne is the builder for deleting a single ProductSubscriptionMigrationSource entity.
type ProductSubscriptionMigrationSourceDeleteOne struct {
	_d *ProductSubscriptionMigrationSourceDelete
}

// Where appends a list predicates to the ProductSubscriptionMigrationSourceDelete builder.
func (_d *ProductSubscriptionMigrationSourceDeleteOne) Where(ps ...predicate.ProductSubscriptionMigrationSource) *ProductSubscriptionMigrationSourceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProductSubscriptionMigrationSourceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productsubscriptionmigrationsource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProductSubscriptionMigrationSourceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
