// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproduct"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproductgroup"
	"github.com/Wei-Shaw/sub2api/ent/userproductsubscription"
)

// SubscriptionProductCreate is the builder for creating a SubscriptionProduct entity.
type SubscriptionProductCreate struct {
	config
	mutation *SubscriptionProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionProductCreate) SetCreatedAt(v time.Time) *SubscriptionProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionProductCreate) SetUpdatedAt(v time.Time) *SubscriptionProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionProductCreate) SetDeletedAt(v time.Time) *SubscriptionProductCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableDeletedAt(v *time.Time) *SubscriptionProductCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *SubscriptionProductCreate) SetCode(v string) *SubscriptionProductCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SubscriptionProductCreate) SetName(v string) *SubscriptionProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SubscriptionProductCreate) SetDescription(v string) *SubscriptionProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableDescription(v *string) *SubscriptionProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionProductCreate) SetStatus(v string) *SubscriptionProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableStatus(v *string) *SubscriptionProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (_c *SubscriptionProductCreate) SetDefaultValidityDays(v int) *SubscriptionProductCreate {
	_c.mutation.SetDefaultValidityDays(v)
	return _c
}

// SetNillableDefaultValidityDays sets the "default_validity_days" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableDefaultValidityDays(v *int) *SubscriptionProductCreate {
	if v != nil {
		_c.SetDefaultValidityDays(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *SubscriptionProductCreate) SetDailyLimitUsd(v float64) *SubscriptionProductCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableDailyLimitUsd(v *float64) *SubscriptionProductCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *SubscriptionProductCreate) SetWeeklyLimitUsd(v float64) *SubscriptionProductCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionProductCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *SubscriptionProductCreate) SetMonthlyLimitUsd(v float64) *SubscriptionProductCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionProductCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SubscriptionProductCreate) SetSortOrder(v int) *SubscriptionProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SubscriptionProductCreate) SetNillableSortOrder(v *int) *SubscriptionProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddGroupBindingIDs adds the "group_bindings" edge to the SubscriptionProductGroup entity by IDs.
func (_c *SubscriptionProductCreate) AddGroupBindingIDs(ids ...int64) *SubscriptionProductCreate {
	_c.mutation.AddGroupBindingIDs(ids...)
	return _c
}

// AddGroupBindings adds the "group_bindings" edges to the SubscriptionProductGroup entity.
func (_c *SubscriptionProductCreate) AddGroupBindings(v ...*SubscriptionProductGroup) *SubscriptionProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupBindingIDs(ids...)
}

// AddUserSubscriptionIDs adds the "user_subscriptions" edge to the UserProductSubscription entity by IDs.
func (_c *SubscriptionProductCreate) AddUserSubscriptionIDs(ids ...int64) *SubscriptionProductCreate {
	_c.mutation.AddUserSubscriptionIDs(ids...)
	return _c
}

// AddUserSubscriptions adds the "user_subscriptions" edges to the UserProductSubscription entity.
func (_c *SubscriptionProductCreate) AddUserSubscriptions(v ...*UserProductSubscription) *SubscriptionProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserSubscriptionIDs(ids...)
}

// Mutation returns the SubscriptionProductMutation object of the builder.
func (_c *SubscriptionProductCreate) Mutation() *SubscriptionProductMutation {
	return _c.mutation
}

// Save creates the SubscriptionProduct in the database.
func (_c *SubscriptionProductCreate) Save(ctx context.Context) (*SubscriptionProduct, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionProductCreate) SaveX(ctx context.Context) *SubscriptionProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionProductCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subscriptionproduct.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproduct.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subscriptionproduct.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproduct.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionproduct.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DefaultValidityDays(); !ok {
		v := subscriptionproduct.DefaultDefaultValidityDays
		_c.mutation.SetDefaultValidityDays(v)
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		v := subscriptionproduct.DefaultDailyLimitUsd
		_c.mutation.SetDailyLimitUsd(v)
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		v := subscriptionproduct.DefaultWeeklyLimitUsd
		_c.mutation.SetWeeklyLimitUsd(v)
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		v := subscriptionproduct.DefaultMonthlyLimitUsd
		_c.mutation.SetMonthlyLimitUsd(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := subscriptionproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionProductCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionProduct.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "SubscriptionProduct.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := subscriptionproduct.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProduct.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubscriptionProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subscriptionproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionProduct.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProduct.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultValidityDays(); !ok {
		return &ValidationError{Name: "default_validity_days", err: errors.New(`ent: missing required field "SubscriptionProduct.default_validity_days"`)}
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		return &ValidationError{Name: "daily_limit_usd", err: errors.New(`ent: missing required field "SubscriptionProduct.daily_limit_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		return &ValidationError{Name: "weekly_limit_usd", err: errors.New(`ent: missing required field "SubscriptionProduct.weekly_limit_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		return &ValidationError{Name: "monthly_limit_usd", err: errors.New(`ent: missing required field "SubscriptionProduct.monthly_limit_usd"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SubscriptionProduct.sort_order"`)}
	}
	return nil
}

func (_c *SubscriptionProductCreate) sqlSave(ctx context.Context) (*SubscriptionProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionProductCreate) createSpec() (*SubscriptionProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionproduct.Table, sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionproduct.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(subscriptionproduct.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subscriptionproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(subscriptionproduct.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionproduct.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DefaultValidityDays(); ok {
		_spec.SetField(subscriptionproduct.FieldDefaultValidityDays, field.TypeInt, value)
		_node.DefaultValidityDays = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionproduct.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionproduct.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionproduct.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.GroupBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionproduct.GroupBindingsTable,
			Columns: []string{subscriptionproduct.GroupBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproductgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionproduct.UserSubscriptionsTable,
			Columns: []string{subscriptionproduct.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userproductsubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionProduct.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionProductCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionProductUpsertOne {
	_c.conflict = opts
	return &SubscriptionProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionProductCreate) OnConflictColumns(columns ...string) *SubscriptionProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionProductUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionProductUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionProduct node.
	SubscriptionProductUpsertOne struct {
		create *SubscriptionProductCreate
	}

	// SubscriptionProductUpsert is the "OnConflict" setter.
	SubscriptionProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductUpsert) SetUpdatedAt(v time.Time) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateUpdatedAt() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductUpsert) SetDeletedAt(v time.Time) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateDeletedAt() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductUpsert) ClearDeletedAt() *SubscriptionProductUpsert {
	u.SetNull(subscriptionproduct.FieldDeletedAt)
	return u
}

// SetCode sets the "code" field.
func (u *SubscriptionProductUpsert) SetCode(v string) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateCode() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *SubscriptionProductUpsert) SetName(v string) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateName() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SubscriptionProductUpsert) SetDescription(v string) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateDescription() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionProductUpsert) ClearDescription() *SubscriptionProductUpsert {
	u.SetNull(subscriptionproduct.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductUpsert) SetStatus(v string) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateStatus() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldStatus)
	return u
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionProductUpsert) SetDefaultValidityDays(v int) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldDefaultValidityDays, v)
	return u
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateDefaultValidityDays() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldDefaultValidityDays)
	return u
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionProductUpsert) AddDefaultValidityDays(v int) *SubscriptionProductUpsert {
	u.Add(subscriptionproduct.FieldDefaultValidityDays, v)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionProductUpsert) SetDailyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateDailyLimitUsd() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionProductUpsert) AddDailyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Add(subscriptionproduct.FieldDailyLimitUsd, v)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsert) SetWeeklyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateWeeklyLimitUsd() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsert) AddWeeklyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Add(subscriptionproduct.FieldWeeklyLimitUsd, v)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsert) SetMonthlyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateMonthlyLimitUsd() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsert) AddMonthlyLimitUsd(v float64) *SubscriptionProductUpsert {
	u.Add(subscriptionproduct.FieldMonthlyLimitUsd, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductUpsert) SetSortOrder(v int) *SubscriptionProductUpsert {
	u.Set(subscriptionproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductUpsert) UpdateSortOrder() *SubscriptionProductUpsert {
	u.SetExcluded(subscriptionproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductUpsert) AddSortOrder(v int) *SubscriptionProductUpsert {
	u.Add(subscriptionproduct.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionProductUpsertOne) UpdateNewValues() *SubscriptionProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionProductUpsertOne) Ignore() *SubscriptionProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionProductUpsertOne) DoNothing() *SubscriptionProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionProductCreate.OnConflict
// documentation for more info.
func (u *SubscriptionProductUpsertOne) Update(set func(*SubscriptionProductUpsert)) *SubscriptionProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateUpdatedAt() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductUpsertOne) SetDeletedAt(v time.Time) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateDeletedAt() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductUpsertOne) ClearDeletedAt() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *SubscriptionProductUpsertOne) SetCode(v string) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateCode() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionProductUpsertOne) SetName(v string) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateName() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubscriptionProductUpsertOne) SetDescription(v string) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateDescription() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionProductUpsertOne) ClearDescription() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductUpsertOne) SetStatus(v string) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateStatus() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateStatus()
	})
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionProductUpsertOne) SetDefaultValidityDays(v int) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDefaultValidityDays(v)
	})
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionProductUpsertOne) AddDefaultValidityDays(v int) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddDefaultValidityDays(v)
	})
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateDefaultValidityDays() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDefaultValidityDays()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionProductUpsertOne) SetDailyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionProductUpsertOne) AddDailyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateDailyLimitUsd() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsertOne) SetWeeklyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsertOne) AddWeeklyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateWeeklyLimitUsd() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsertOne) SetMonthlyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsertOne) AddMonthlyLimitUsd(v float64) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateMonthlyLimitUsd() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductUpsertOne) SetSortOrder(v int) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductUpsertOne) AddSortOrder(v int) *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductUpsertOne) UpdateSortOrder() *SubscriptionProductUpsertOne {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionProductCreateBulk is the builder for creating many SubscriptionProduct entities in bulk.
type SubscriptionProductCreateBulk struct {
	config
	err      error
	builders []*SubscriptionProductCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionProduct entities in the database.
func (_c *SubscriptionProductCreateBulk) Save(ctx context.Context) ([]*SubscriptionProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionProductCreateBulk) SaveX(ctx context.Context) []*SubscriptionProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionProductUpsertBulk {
	_c.conflict = opts
	return &SubscriptionProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionProductCreateBulk) OnConflictColumns(columns ...string) *SubscriptionProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionProductUpsertBulk{
		create: _c,
	}
}

// SubscriptionProductUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionProduct nodes.
type SubscriptionProductUpsertBulk struct {
	create *SubscriptionProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionProductUpsertBulk) UpdateNewValues() *SubscriptionProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionProductUpsertBulk) Ignore() *SubscriptionProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionProductUpsertBulk) DoNothing() *SubscriptionProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionProductCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionProductUpsertBulk) Update(set func(*SubscriptionProductUpsert)) *SubscriptionProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateUpdatedAt() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductUpsertBulk) SetDeletedAt(v time.Time) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateDeletedAt() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductUpsertBulk) ClearDeletedAt() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *SubscriptionProductUpsertBulk) SetCode(v string) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateCode() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionProductUpsertBulk) SetName(v string) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateName() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubscriptionProductUpsertBulk) SetDescription(v string) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateDescription() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionProductUpsertBulk) ClearDescription() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductUpsertBulk) SetStatus(v string) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateStatus() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateStatus()
	})
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionProductUpsertBulk) SetDefaultValidityDays(v int) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDefaultValidityDays(v)
	})
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionProductUpsertBulk) AddDefaultValidityDays(v int) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddDefaultValidityDays(v)
	})
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateDefaultValidityDays() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDefaultValidityDays()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) SetDailyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) AddDailyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateDailyLimitUsd() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) SetWeeklyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) AddWeeklyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateWeeklyLimitUsd() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) SetMonthlyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionProductUpsertBulk) AddMonthlyLimitUsd(v float64) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateMonthlyLimitUsd() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductUpsertBulk) SetSortOrder(v int) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductUpsertBulk) AddSortOrder(v int) *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductUpsertBulk) UpdateSortOrder() *SubscriptionProductUpsertBulk {
	return u.Update(func(s *SubscriptionProductUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
