// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproduct"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproductgroup"
)

// SubscriptionProductGroupUpdate is the builder for updating SubscriptionProductGroup entities.
type SubscriptionProductGroupUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionProductGroupMutation
}

// Where appends a list predicates to the SubscriptionProductGroupUpdate builder.
func (_u *SubscriptionProductGroupUpdate) Where(ps ...predicate.SubscriptionProductGroup) *SubscriptionProductGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionProductGroupUpdate) SetUpdatedAt(v time.Time) *SubscriptionProductGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionProductGroupUpdate) SetDeletedAt(v time.Time) *SubscriptionProductGroupUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableDeletedAt(v *time.Time) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionProductGroupUpdate) ClearDeletedAt() *SubscriptionProductGroupUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *SubscriptionProductGroupUpdate) SetProductID(v int64) *SubscriptionProductGroupUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableProductID(v *int64) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionProductGroupUpdate) SetGroupID(v int64) *SubscriptionProductGroupUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableGroupID(v *int64) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionProductGroupUpdate) AddGroupID(v int64) *SubscriptionProductGroupUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (_u *SubscriptionProductGroupUpdate) SetDebitMultiplier(v float64) *SubscriptionProductGroupUpdate {
	_u.mutation.ResetDebitMultiplier()
	_u.mutation.SetDebitMultiplier(v)
	return _u
}

// SetNillableDebitMultiplier sets the "debit_multiplier" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableDebitMultiplier(v *float64) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetDebitMultiplier(*v)
	}
	return _u
}

// AddDebitMultiplier adds value to the "debit_multiplier" field.
func (_u *SubscriptionProductGroupUpdate) AddDebitMultiplier(v float64) *SubscriptionProductGroupUpdate {
	_u.mutation.AddDebitMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionProductGroupUpdate) SetStatus(v string) *SubscriptionProductGroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableStatus(v *string) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionProductGroupUpdate) SetSortOrder(v int) *SubscriptionProductGroupUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdate) SetNillableSortOrder(v *int) *SubscriptionProductGroupUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionProductGroupUpdate) AddSortOrder(v int) *SubscriptionProductGroupUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetProduct sets the "product" edge to the SubscriptionProduct entity.
func (_u *SubscriptionProductGroupUpdate) SetProduct(v *SubscriptionProduct) *SubscriptionProductGroupUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the SubscriptionProductGroupMutation object of the builder.
func (_u *SubscriptionProductGroupUpdate) Mutation() *SubscriptionProductGroupMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the SubscriptionProduct entity.
func (_u *SubscriptionProductGroupUpdate) ClearProduct() *SubscriptionProductGroupUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionProductGroupUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionProductGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionProductGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionProductGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionProductGroupUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionproductgroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproductgroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproductgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionProductGroupUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionproductgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProductGroup.status": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionProductGroup.product"`)
	}
	return nil
}

func (_u *SubscriptionProductGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionproductgroup.Table, subscriptionproductgroup.Columns, sqlgraph.NewFieldSpec(subscriptionproductgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionproductgroup.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionproductgroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionproductgroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebitMultiplier(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDebitMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitMultiplier(); ok {
		_spec.AddField(subscriptionproductgroup.FieldDebitMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionproductgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionproductgroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionproductgroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionproductgroup.ProductTable,
			Columns: []string{subscriptionproductgroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionproductgroup.ProductTable,
			Columns: []string{subscriptionproductgroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionproductgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionProductGroupUpdateOne is the builder for updating a single SubscriptionProductGroup entity.
type SubscriptionProductGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionProductGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionProductGroupUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionProductGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionProductGroupUpdateOne) SetDeletedAt(v time.Time) *SubscriptionProductGroupUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableDeletedAt(v *time.Time) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionProductGroupUpdateOne) ClearDeletedAt() *SubscriptionProductGroupUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *SubscriptionProductGroupUpdateOne) SetProductID(v int64) *SubscriptionProductGroupUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableProductID(v *int64) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionProductGroupUpdateOne) SetGroupID(v int64) *SubscriptionProductGroupUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableGroupID(v *int64) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionProductGroupUpdateOne) AddGroupID(v int64) *SubscriptionProductGroupUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (_u *SubscriptionProductGroupUpdateOne) SetDebitMultiplier(v float64) *SubscriptionProductGroupUpdateOne {
	_u.mutation.ResetDebitMultiplier()
	_u.mutation.SetDebitMultiplier(v)
	return _u
}

// SetNillableDebitMultiplier sets the "debit_multiplier" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableDebitMultiplier(v *float64) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetDebitMultiplier(*v)
	}
	return _u
}

// AddDebitMultiplier adds value to the "debit_multiplier" field.
func (_u *SubscriptionProductGroupUpdateOne) AddDebitMultiplier(v float64) *SubscriptionProductGroupUpdateOne {
	_u.mutation.AddDebitMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionProductGroupUpdateOne) SetStatus(v string) *SubscriptionProductGroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableStatus(v *string) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionProductGroupUpdateOne) SetSortOrder(v int) *SubscriptionProductGroupUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionProductGroupUpdateOne) SetNillableSortOrder(v *int) *SubscriptionProductGroupUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionProductGroupUpdateOne) AddSortOrder(v int) *SubscriptionProductGroupUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetProduct sets the "product" edge to the SubscriptionProduct entity.
func (_u *SubscriptionProductGroupUpdateOne) SetProduct(v *SubscriptionProduct) *SubscriptionProductGroupUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the SubscriptionProductGroupMutation object of the builder.
func (_u *SubscriptionProductGroupUpdateOne) Mutation() *SubscriptionProductGroupMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the SubscriptionProduct entity.
func (_u *SubscriptionProductGroupUpdateOne) ClearProduct() *SubscriptionProductGroupUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the SubscriptionProductGroupUpdate builder.
func (_u *SubscriptionProductGroupUpdateOne) Where(ps ...predicate.SubscriptionProductGroup) *SubscriptionProductGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionProductGroupUpdateOne) Select(field string, fields ...string) *SubscriptionProductGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionProductGroup entity.
func (_u *SubscriptionProductGroupUpdateOne) Save(ctx context.Context) (*SubscriptionProductGroup, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionProductGroupUpdateOne) SaveX(ctx context.Context) *SubscriptionProductGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionProductGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionProductGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionProductGroupUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionproductgroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproductgroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproductgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionProductGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionproductgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProductGroup.status": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionProductGroup.product"`)
	}
	return nil
}

func (_u *SubscriptionProductGroupUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionProductGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionproductgroup.Table, subscriptionproductgroup.Columns, sqlgraph.NewFieldSpec(subscriptionproductgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionProductGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionproductgroup.FieldID)
		for _, f := range fields {
			if !subscriptionproductgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionproductgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionproductgroup.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionproductgroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionproductgroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebitMultiplier(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDebitMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitMultiplier(); ok {
		_spec.AddField(subscriptionproductgroup.FieldDebitMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionproductgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionproductgroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionproductgroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionproductgroup.ProductTable,
			Columns: []string{subscriptionproductgroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionproductgroup.ProductTable,
			Columns: []string{subscriptionproductgroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionProductGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionproductgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
