// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproduct"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproductgroup"
)

// SubscriptionProductGroupCreate is the builder for creating a SubscriptionProductGroup entity.
type SubscriptionProductGroupCreate struct {
	config
	mutation *SubscriptionProductGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionProductGroupCreate) SetCreatedAt(v time.Time) *SubscriptionProductGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionProductGroupCreate) SetUpdatedAt(v time.Time) *SubscriptionProductGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionProductGroupCreate) SetDeletedAt(v time.Time) *SubscriptionProductGroupCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableDeletedAt(v *time.Time) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *SubscriptionProductGroupCreate) SetProductID(v int64) *SubscriptionProductGroupCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionProductGroupCreate) SetGroupID(v int64) *SubscriptionProductGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (_c *SubscriptionProductGroupCreate) SetDebitMultiplier(v float64) *SubscriptionProductGroupCreate {
	_c.mutation.SetDebitMultiplier(v)
	return _c
}

// SetNillableDebitMultiplier sets the "debit_multiplier" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableDebitMultiplier(v *float64) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetDebitMultiplier(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionProductGroupCreate) SetStatus(v string) *SubscriptionProductGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableStatus(v *string) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SubscriptionProductGroupCreate) SetSortOrder(v int) *SubscriptionProductGroupCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SubscriptionProductGroupCreate) SetNillableSortOrder(v *int) *SubscriptionProductGroupCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the SubscriptionProduct entity.
func (_c *SubscriptionProductGroupCreate) SetProduct(v *SubscriptionProduct) *SubscriptionProductGroupCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the SubscriptionProductGroupMutation object of the builder.
func (_c *SubscriptionProductGroupCreate) Mutation() *SubscriptionProductGroupMutation {
	return _c.mutation
}

// Save creates the SubscriptionProductGroup in the database.
func (_c *SubscriptionProductGroupCreate) Save(ctx context.Context) (*SubscriptionProductGroup, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionProductGroupCreate) SaveX(ctx context.Context) *SubscriptionProductGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionProductGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionProductGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionProductGroupCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subscriptionproductgroup.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproductgroup.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproductgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subscriptionproductgroup.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionproductgroup.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionproductgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DebitMultiplier(); !ok {
		v := subscriptionproductgroup.DefaultDebitMultiplier
		_c.mutation.SetDebitMultiplier(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionproductgroup.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := subscriptionproductgroup.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionProductGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionProductGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionProductGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "SubscriptionProductGroup.product_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionProductGroup.group_id"`)}
	}
	if _, ok := _c.mutation.DebitMultiplier(); !ok {
		return &ValidationError{Name: "debit_multiplier", err: errors.New(`ent: missing required field "SubscriptionProductGroup.debit_multiplier"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionProductGroup.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionproductgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionProductGroup.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SubscriptionProductGroup.sort_order"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "SubscriptionProductGroup.product"`)}
	}
	return nil
}

func (_c *SubscriptionProductGroupCreate) sqlSave(ctx context.Context) (*SubscriptionProductGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionProductGroupCreate) createSpec() (*SubscriptionProductGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionProductGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionproductgroup.Table, sqlgraph.NewFieldSpec(subscriptionproductgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(subscriptionproductgroup.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.DebitMultiplier(); ok {
		_spec.SetField(subscriptionproductgroup.FieldDebitMultiplier, field.TypeFloat64, value)
		_node.DebitMultiplier = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionproductgroup.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionproductgroup.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionproductgroup.ProductTable,
			Columns: []string{subscriptionproductgroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionProductGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionProductGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionProductGroupCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionProductGroupUpsertOne {
	_c.conflict = opts
	return &SubscriptionProductGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionProductGroupCreate) OnConflictColumns(columns ...string) *SubscriptionProductGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionProductGroupUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionProductGroupUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionProductGroup node.
	SubscriptionProductGroupUpsertOne struct {
		create *SubscriptionProductGroupCreate
	}

	// SubscriptionProductGroupUpsert is the "OnConflict" setter.
	SubscriptionProductGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductGroupUpsert) SetUpdatedAt(v time.Time) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateUpdatedAt() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductGroupUpsert) SetDeletedAt(v time.Time) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateDeletedAt() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductGroupUpsert) ClearDeletedAt() *SubscriptionProductGroupUpsert {
	u.SetNull(subscriptionproductgroup.FieldDeletedAt)
	return u
}

// SetProductID sets the "product_id" field.
func (u *SubscriptionProductGroupUpsert) SetProductID(v int64) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateProductID() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldProductID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionProductGroupUpsert) SetGroupID(v int64) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateGroupID() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionProductGroupUpsert) AddGroupID(v int64) *SubscriptionProductGroupUpsert {
	u.Add(subscriptionproductgroup.FieldGroupID, v)
	return u
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsert) SetDebitMultiplier(v float64) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldDebitMultiplier, v)
	return u
}

// UpdateDebitMultiplier sets the "debit_multiplier" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateDebitMultiplier() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldDebitMultiplier)
	return u
}

// AddDebitMultiplier adds v to the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsert) AddDebitMultiplier(v float64) *SubscriptionProductGroupUpsert {
	u.Add(subscriptionproductgroup.FieldDebitMultiplier, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductGroupUpsert) SetStatus(v string) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateStatus() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductGroupUpsert) SetSortOrder(v int) *SubscriptionProductGroupUpsert {
	u.Set(subscriptionproductgroup.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsert) UpdateSortOrder() *SubscriptionProductGroupUpsert {
	u.SetExcluded(subscriptionproductgroup.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductGroupUpsert) AddSortOrder(v int) *SubscriptionProductGroupUpsert {
	u.Add(subscriptionproductgroup.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionProductGroupUpsertOne) UpdateNewValues() *SubscriptionProductGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionproductgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionProductGroupUpsertOne) Ignore() *SubscriptionProductGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionProductGroupUpsertOne) DoNothing() *SubscriptionProductGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionProductGroupCreate.OnConflict
// documentation for more info.
func (u *SubscriptionProductGroupUpsertOne) Update(set func(*SubscriptionProductGroupUpsert)) *SubscriptionProductGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionProductGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductGroupUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateUpdatedAt() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductGroupUpsertOne) SetDeletedAt(v time.Time) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateDeletedAt() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductGroupUpsertOne) ClearDeletedAt() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.ClearDeletedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *SubscriptionProductGroupUpsertOne) SetProductID(v int64) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateProductID() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateProductID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionProductGroupUpsertOne) SetGroupID(v int64) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionProductGroupUpsertOne) AddGroupID(v int64) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateGroupID() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsertOne) SetDebitMultiplier(v float64) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetDebitMultiplier(v)
	})
}

// AddDebitMultiplier adds v to the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsertOne) AddDebitMultiplier(v float64) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddDebitMultiplier(v)
	})
}

// UpdateDebitMultiplier sets the "debit_multiplier" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateDebitMultiplier() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateDebitMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductGroupUpsertOne) SetStatus(v string) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateStatus() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductGroupUpsertOne) SetSortOrder(v int) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductGroupUpsertOne) AddSortOrder(v int) *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertOne) UpdateSortOrder() *SubscriptionProductGroupUpsertOne {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionProductGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionProductGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionProductGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionProductGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionProductGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionProductGroupCreateBulk is the builder for creating many SubscriptionProductGroup entities in bulk.
type SubscriptionProductGroupCreateBulk struct {
	config
	err      error
	builders []*SubscriptionProductGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionProductGroup entities in the database.
func (_c *SubscriptionProductGroupCreateBulk) Save(ctx context.Context) ([]*SubscriptionProductGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionProductGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionProductGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionProductGroupCreateBulk) SaveX(ctx context.Context) []*SubscriptionProductGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionProductGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionProductGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionProductGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionProductGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionProductGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionProductGroupUpsertBulk {
	_c.conflict = opts
	return &SubscriptionProductGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionProductGroupCreateBulk) OnConflictColumns(columns ...string) *SubscriptionProductGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionProductGroupUpsertBulk{
		create: _c,
	}
}

// SubscriptionProductGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionProductGroup nodes.
type SubscriptionProductGroupUpsertBulk struct {
	create *SubscriptionProductGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionProductGroupUpsertBulk) UpdateNewValues() *SubscriptionProductGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionproductgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionProductGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionProductGroupUpsertBulk) Ignore() *SubscriptionProductGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionProductGroupUpsertBulk) DoNothing() *SubscriptionProductGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionProductGroupCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionProductGroupUpsertBulk) Update(set func(*SubscriptionProductGroupUpsert)) *SubscriptionProductGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionProductGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionProductGroupUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateUpdatedAt() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionProductGroupUpsertBulk) SetDeletedAt(v time.Time) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateDeletedAt() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionProductGroupUpsertBulk) ClearDeletedAt() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.ClearDeletedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *SubscriptionProductGroupUpsertBulk) SetProductID(v int64) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateProductID() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateProductID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionProductGroupUpsertBulk) SetGroupID(v int64) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionProductGroupUpsertBulk) AddGroupID(v int64) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateGroupID() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetDebitMultiplier sets the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsertBulk) SetDebitMultiplier(v float64) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetDebitMultiplier(v)
	})
}

// AddDebitMultiplier adds v to the "debit_multiplier" field.
func (u *SubscriptionProductGroupUpsertBulk) AddDebitMultiplier(v float64) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddDebitMultiplier(v)
	})
}

// UpdateDebitMultiplier sets the "debit_multiplier" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateDebitMultiplier() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateDebitMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionProductGroupUpsertBulk) SetStatus(v string) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateStatus() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionProductGroupUpsertBulk) SetSortOrder(v int) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionProductGroupUpsertBulk) AddSortOrder(v int) *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionProductGroupUpsertBulk) UpdateSortOrder() *SubscriptionProductGroupUpsertBulk {
	return u.Update(func(s *SubscriptionProductGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionProductGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionProductGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionProductGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionProductGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
