// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproduct"
)

// SubscriptionProduct is the model entity for the SubscriptionProduct schema.
type SubscriptionProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// DefaultValidityDays holds the value of the "default_validity_days" field.
	DefaultValidityDays int `json:"default_validity_days,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd float64 `json:"monthly_limit_usd,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionProductQuery when eager-loading is set.
	Edges        SubscriptionProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionProductEdges holds the relations/edges for other nodes in the graph.
type SubscriptionProductEdges struct {
	// GroupBindings holds the value of the group_bindings edge.
	GroupBindings []*SubscriptionProductGroup `json:"group_bindings,omitempty"`
	// UserSubscriptions holds the value of the user_subscriptions edge.
	UserSubscriptions []*UserProductSubscription `json:"user_subscriptions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupBindingsOrErr returns the GroupBindings value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionProductEdges) GroupBindingsOrErr() ([]*SubscriptionProductGroup, error) {
	if e.loadedTypes[0] {
		return e.GroupBindings, nil
	}
	return nil, &NotLoadedError{edge: "group_bindings"}
}

// UserSubscriptionsOrErr returns the UserSubscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionProductEdges) UserSubscriptionsOrErr() ([]*UserProductSubscription, error) {
	if e.loadedTypes[1] {
		return e.UserSubscriptions, nil
	}
	return nil, &NotLoadedError{edge: "user_subscriptions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionproduct.FieldDailyLimitUsd, subscriptionproduct.FieldWeeklyLimitUsd, subscriptionproduct.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptionproduct.FieldID, subscriptionproduct.FieldDefaultValidityDays, subscriptionproduct.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case subscriptionproduct.FieldCode, subscriptionproduct.FieldName, subscriptionproduct.FieldDescription, subscriptionproduct.FieldStatus:
			values[i] = new(sql.NullString)
		case subscriptionproduct.FieldCreatedAt, subscriptionproduct.FieldUpdatedAt, subscriptionproduct.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionProduct fields.
func (_m *SubscriptionProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionproduct.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case subscriptionproduct.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case subscriptionproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subscriptionproduct.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case subscriptionproduct.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionproduct.FieldDefaultValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_validity_days", values[i])
			} else if value.Valid {
				_m.DefaultValidityDays = int(value.Int64)
			}
		case subscriptionproduct.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = value.Float64
			}
		case subscriptionproduct.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = value.Float64
			}
		case subscriptionproduct.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = value.Float64
			}
		case subscriptionproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionProduct.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroupBindings queries the "group_bindings" edge of the SubscriptionProduct entity.
func (_m *SubscriptionProduct) QueryGroupBindings() *SubscriptionProductGroupQuery {
	return NewSubscriptionProductClient(_m.config).QueryGroupBindings(_m)
}

// QueryUserSubscriptions queries the "user_subscriptions" edge of the SubscriptionProduct entity.
func (_m *SubscriptionProduct) QueryUserSubscriptions() *UserProductSubscriptionQuery {
	return NewSubscriptionProductClient(_m.config).QueryUserSubscriptions(_m)
}

// Update returns a builder for updating this SubscriptionProduct.
// Note that you need to call SubscriptionProduct.Unwrap() before calling this method if this SubscriptionProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionProduct) Update() *SubscriptionProductUpdateOne {
	return NewSubscriptionProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionProduct) Unwrap() *SubscriptionProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionProduct) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("default_validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultValidityDays))
	builder.WriteString(", ")
	builder.WriteString("daily_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionProducts is a parsable slice of SubscriptionProduct.
type SubscriptionProducts []*SubscriptionProduct
