// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/productsubscriptionmigrationsource"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionproduct"
	"github.com/Wei-Shaw/sub2api/ent/userproductsubscription"
)

// UserProductSubscriptionCreate is the builder for creating a UserProductSubscription entity.
type UserProductSubscriptionCreate struct {
	config
	mutation *UserProductSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserProductSubscriptionCreate) SetCreatedAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserProductSubscriptionCreate) SetUpdatedAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserProductSubscriptionCreate) SetDeletedAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableDeletedAt(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserProductSubscriptionCreate) SetUserID(v int64) *UserProductSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *UserProductSubscriptionCreate) SetProductID(v int64) *UserProductSubscriptionCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserProductSubscriptionCreate) SetStartsAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserProductSubscriptionCreate) SetExpiresAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserProductSubscriptionCreate) SetStatus(v string) *UserProductSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableStatus(v *string) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *UserProductSubscriptionCreate) SetDailyWindowStart(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableDailyWindowStart(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *UserProductSubscriptionCreate) SetWeeklyWindowStart(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableWeeklyWindowStart(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *UserProductSubscriptionCreate) SetMonthlyWindowStart(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableMonthlyWindowStart(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *UserProductSubscriptionCreate) SetDailyUsageUsd(v float64) *UserProductSubscriptionCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableDailyUsageUsd(v *float64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *UserProductSubscriptionCreate) SetWeeklyUsageUsd(v float64) *UserProductSubscriptionCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableWeeklyUsageUsd(v *float64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *UserProductSubscriptionCreate) SetMonthlyUsageUsd(v float64) *UserProductSubscriptionCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableMonthlyUsageUsd(v *float64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetDailyCarryoverInUsd sets the "daily_carryover_in_usd" field.
func (_c *UserProductSubscriptionCreate) SetDailyCarryoverInUsd(v float64) *UserProductSubscriptionCreate {
	_c.mutation.SetDailyCarryoverInUsd(v)
	return _c
}

// SetNillableDailyCarryoverInUsd sets the "daily_carryover_in_usd" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableDailyCarryoverInUsd(v *float64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetDailyCarryoverInUsd(*v)
	}
	return _c
}

// SetDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field.
func (_c *UserProductSubscriptionCreate) SetDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionCreate {
	_c.mutation.SetDailyCarryoverRemainingUsd(v)
	return _c
}

// SetNillableDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableDailyCarryoverRemainingUsd(v *float64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetDailyCarryoverRemainingUsd(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *UserProductSubscriptionCreate) SetAssignedBy(v int64) *UserProductSubscriptionCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableAssignedBy(v *int64) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *UserProductSubscriptionCreate) SetAssignedAt(v time.Time) *UserProductSubscriptionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableAssignedAt(v *time.Time) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserProductSubscriptionCreate) SetNotes(v string) *UserProductSubscriptionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserProductSubscriptionCreate) SetNillableNotes(v *string) *UserProductSubscriptionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the SubscriptionProduct entity.
func (_c *UserProductSubscriptionCreate) SetProduct(v *SubscriptionProduct) *UserProductSubscriptionCreate {
	return _c.SetProductID(v.ID)
}

// AddMigrationSourceIDs adds the "migration_sources" edge to the ProductSubscriptionMigrationSource entity by IDs.
func (_c *UserProductSubscriptionCreate) AddMigrationSourceIDs(ids ...int64) *UserProductSubscriptionCreate {
	_c.mutation.AddMigrationSourceIDs(ids...)
	return _c
}

// AddMigrationSources adds the "migration_sources" edges to the ProductSubscriptionMigrationSource entity.
func (_c *UserProductSubscriptionCreate) AddMigrationSources(v ...*ProductSubscriptionMigrationSource) *UserProductSubscriptionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMigrationSourceIDs(ids...)
}

// Mutation returns the UserProductSubscriptionMutation object of the builder.
func (_c *UserProductSubscriptionCreate) Mutation() *UserProductSubscriptionMutation {
	return _c.mutation
}

// Save creates the UserProductSubscription in the database.
func (_c *UserProductSubscriptionCreate) Save(ctx context.Context) (*UserProductSubscription, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserProductSubscriptionCreate) SaveX(ctx context.Context) *UserProductSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProductSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProductSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserProductSubscriptionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if userproductsubscription.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized userproductsubscription.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := userproductsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if userproductsubscription.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userproductsubscription.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userproductsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userproductsubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := userproductsubscription.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := userproductsubscription.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := userproductsubscription.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.DailyCarryoverInUsd(); !ok {
		v := userproductsubscription.DefaultDailyCarryoverInUsd
		_c.mutation.SetDailyCarryoverInUsd(v)
	}
	if _, ok := _c.mutation.DailyCarryoverRemainingUsd(); !ok {
		v := userproductsubscription.DefaultDailyCarryoverRemainingUsd
		_c.mutation.SetDailyCarryoverRemainingUsd(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		if userproductsubscription.DefaultAssignedAt == nil {
			return fmt.Errorf("ent: uninitialized userproductsubscription.DefaultAssignedAt (forgotten import ent/runtime?)")
		}
		v := userproductsubscription.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserProductSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserProductSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserProductSubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserProductSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "UserProductSubscription.product_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserProductSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserProductSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserProductSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userproductsubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserProductSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "UserProductSubscription.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "UserProductSubscription.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "UserProductSubscription.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.DailyCarryoverInUsd(); !ok {
		return &ValidationError{Name: "daily_carryover_in_usd", err: errors.New(`ent: missing required field "UserProductSubscription.daily_carryover_in_usd"`)}
	}
	if _, ok := _c.mutation.DailyCarryoverRemainingUsd(); !ok {
		return &ValidationError{Name: "daily_carryover_remaining_usd", err: errors.New(`ent: missing required field "UserProductSubscription.daily_carryover_remaining_usd"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "UserProductSubscription.assigned_at"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "UserProductSubscription.product"`)}
	}
	return nil
}

func (_c *UserProductSubscriptionCreate) sqlSave(ctx context.Context) (*UserProductSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserProductSubscriptionCreate) createSpec() (*UserProductSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &UserProductSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userproductsubscription.Table, sqlgraph.NewFieldSpec(userproductsubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userproductsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userproductsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(userproductsubscription.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userproductsubscription.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(userproductsubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userproductsubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userproductsubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(userproductsubscription.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(userproductsubscription.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(userproductsubscription.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(userproductsubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(userproductsubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(userproductsubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.DailyCarryoverInUsd(); ok {
		_spec.SetField(userproductsubscription.FieldDailyCarryoverInUsd, field.TypeFloat64, value)
		_node.DailyCarryoverInUsd = value
	}
	if value, ok := _c.mutation.DailyCarryoverRemainingUsd(); ok {
		_spec.SetField(userproductsubscription.FieldDailyCarryoverRemainingUsd, field.TypeFloat64, value)
		_node.DailyCarryoverRemainingUsd = value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(userproductsubscription.FieldAssignedBy, field.TypeInt64, value)
		_node.AssignedBy = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(userproductsubscription.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(userproductsubscription.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userproductsubscription.ProductTable,
			Columns: []string{userproductsubscription.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MigrationSourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userproductsubscription.MigrationSourcesTable,
			Columns: []string{userproductsubscription.MigrationSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productsubscriptionmigrationsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserProductSubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserProductSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserProductSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *UserProductSubscriptionUpsertOne {
	_c.conflict = opts
	return &UserProductSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserProductSubscriptionCreate) OnConflictColumns(columns ...string) *UserProductSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserProductSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// UserProductSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one UserProductSubscription node.
	UserProductSubscriptionUpsertOne struct {
		create *UserProductSubscriptionCreate
	}

	// UserProductSubscriptionUpsert is the "OnConflict" setter.
	UserProductSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserProductSubscriptionUpsert) SetUpdatedAt(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateUpdatedAt() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserProductSubscriptionUpsert) SetDeletedAt(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateDeletedAt() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserProductSubscriptionUpsert) ClearDeletedAt() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserProductSubscriptionUpsert) SetUserID(v int64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateUserID() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserProductSubscriptionUpsert) AddUserID(v int64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldUserID, v)
	return u
}

// SetProductID sets the "product_id" field.
func (u *UserProductSubscriptionUpsert) SetProductID(v int64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateProductID() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldProductID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserProductSubscriptionUpsert) SetStartsAt(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateStartsAt() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserProductSubscriptionUpsert) SetExpiresAt(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateExpiresAt() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserProductSubscriptionUpsert) SetStatus(v string) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateStatus() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldStatus)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserProductSubscriptionUpsert) SetDailyWindowStart(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateDailyWindowStart() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserProductSubscriptionUpsert) ClearDailyWindowStart() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsert) SetWeeklyWindowStart(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateWeeklyWindowStart() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsert) ClearWeeklyWindowStart() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsert) SetMonthlyWindowStart(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateMonthlyWindowStart() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsert) ClearMonthlyWindowStart() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldMonthlyWindowStart)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsert) SetDailyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateDailyUsageUsd() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsert) AddDailyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsert) SetWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateWeeklyUsageUsd() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsert) AddWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsert) SetMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateMonthlyUsageUsd() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsert) AddMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldMonthlyUsageUsd, v)
	return u
}

// SetDailyCarryoverInUsd sets the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsert) SetDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldDailyCarryoverInUsd, v)
	return u
}

// UpdateDailyCarryoverInUsd sets the "daily_carryover_in_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateDailyCarryoverInUsd() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldDailyCarryoverInUsd)
	return u
}

// AddDailyCarryoverInUsd adds v to the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsert) AddDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldDailyCarryoverInUsd, v)
	return u
}

// SetDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsert) SetDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldDailyCarryoverRemainingUsd, v)
	return u
}

// UpdateDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateDailyCarryoverRemainingUsd() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldDailyCarryoverRemainingUsd)
	return u
}

// AddDailyCarryoverRemainingUsd adds v to the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsert) AddDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldDailyCarryoverRemainingUsd, v)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserProductSubscriptionUpsert) SetAssignedBy(v int64) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateAssignedBy() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldAssignedBy)
	return u
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *UserProductSubscriptionUpsert) AddAssignedBy(v int64) *UserProductSubscriptionUpsert {
	u.Add(userproductsubscription.FieldAssignedBy, v)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserProductSubscriptionUpsert) ClearAssignedBy() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldAssignedBy)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserProductSubscriptionUpsert) SetAssignedAt(v time.Time) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateAssignedAt() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldAssignedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserProductSubscriptionUpsert) SetNotes(v string) *UserProductSubscriptionUpsert {
	u.Set(userproductsubscription.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsert) UpdateNotes() *UserProductSubscriptionUpsert {
	u.SetExcluded(userproductsubscription.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UserProductSubscriptionUpsert) ClearNotes() *UserProductSubscriptionUpsert {
	u.SetNull(userproductsubscription.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserProductSubscriptionUpsertOne) UpdateNewValues() *UserProductSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userproductsubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserProductSubscriptionUpsertOne) Ignore() *UserProductSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserProductSubscriptionUpsertOne) DoNothing() *UserProductSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserProductSubscriptionCreate.OnConflict
// documentation for more info.
func (u *UserProductSubscriptionUpsertOne) Update(set func(*UserProductSubscriptionUpsert)) *UserProductSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserProductSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserProductSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateUpdatedAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserProductSubscriptionUpsertOne) SetDeletedAt(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateDeletedAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserProductSubscriptionUpsertOne) ClearDeletedAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserProductSubscriptionUpsertOne) SetUserID(v int64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserProductSubscriptionUpsertOne) AddUserID(v int64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateUserID() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *UserProductSubscriptionUpsertOne) SetProductID(v int64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateProductID() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateProductID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserProductSubscriptionUpsertOne) SetStartsAt(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateStartsAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserProductSubscriptionUpsertOne) SetExpiresAt(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateExpiresAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserProductSubscriptionUpsertOne) SetStatus(v string) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateStatus() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserProductSubscriptionUpsertOne) SetDailyWindowStart(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateDailyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserProductSubscriptionUpsertOne) ClearDailyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsertOne) SetWeeklyWindowStart(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateWeeklyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsertOne) ClearWeeklyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsertOne) SetMonthlyWindowStart(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateMonthlyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsertOne) ClearMonthlyWindowStart() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) SetDailyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) AddDailyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateDailyUsageUsd() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) SetWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) AddWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateWeeklyUsageUsd() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) SetMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsertOne) AddMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateMonthlyUsageUsd() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyCarryoverInUsd sets the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsertOne) SetDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyCarryoverInUsd(v)
	})
}

// AddDailyCarryoverInUsd adds v to the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsertOne) AddDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyCarryoverInUsd(v)
	})
}

// UpdateDailyCarryoverInUsd sets the "daily_carryover_in_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateDailyCarryoverInUsd() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyCarryoverInUsd()
	})
}

// SetDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsertOne) SetDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyCarryoverRemainingUsd(v)
	})
}

// AddDailyCarryoverRemainingUsd adds v to the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsertOne) AddDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyCarryoverRemainingUsd(v)
	})
}

// UpdateDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateDailyCarryoverRemainingUsd() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyCarryoverRemainingUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserProductSubscriptionUpsertOne) SetAssignedBy(v int64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *UserProductSubscriptionUpsertOne) AddAssignedBy(v int64) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateAssignedBy() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserProductSubscriptionUpsertOne) ClearAssignedBy() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserProductSubscriptionUpsertOne) SetAssignedAt(v time.Time) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateAssignedAt() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserProductSubscriptionUpsertOne) SetNotes(v string) *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertOne) UpdateNotes() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserProductSubscriptionUpsertOne) ClearNotes() *UserProductSubscriptionUpsertOne {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *UserProductSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserProductSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserProductSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserProductSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserProductSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserProductSubscriptionCreateBulk is the builder for creating many UserProductSubscription entities in bulk.
type UserProductSubscriptionCreateBulk struct {
	config
	err      error
	builders []*UserProductSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserProductSubscription entities in the database.
func (_c *UserProductSubscriptionCreateBulk) Save(ctx context.Context) ([]*UserProductSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserProductSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserProductSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserProductSubscriptionCreateBulk) SaveX(ctx context.Context) []*UserProductSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProductSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProductSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserProductSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserProductSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserProductSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserProductSubscriptionUpsertBulk {
	_c.conflict = opts
	return &UserProductSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserProductSubscriptionCreateBulk) OnConflictColumns(columns ...string) *UserProductSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserProductSubscriptionUpsertBulk{
		create: _c,
	}
}

// UserProductSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserProductSubscription nodes.
type UserProductSubscriptionUpsertBulk struct {
	create *UserProductSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserProductSubscriptionUpsertBulk) UpdateNewValues() *UserProductSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userproductsubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserProductSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserProductSubscriptionUpsertBulk) Ignore() *UserProductSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserProductSubscriptionUpsertBulk) DoNothing() *UserProductSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserProductSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *UserProductSubscriptionUpsertBulk) Update(set func(*UserProductSubscriptionUpsert)) *UserProductSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserProductSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserProductSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateUpdatedAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserProductSubscriptionUpsertBulk) SetDeletedAt(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateDeletedAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserProductSubscriptionUpsertBulk) ClearDeletedAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserProductSubscriptionUpsertBulk) SetUserID(v int64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserProductSubscriptionUpsertBulk) AddUserID(v int64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateUserID() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *UserProductSubscriptionUpsertBulk) SetProductID(v int64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateProductID() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateProductID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserProductSubscriptionUpsertBulk) SetStartsAt(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateStartsAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserProductSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateExpiresAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserProductSubscriptionUpsertBulk) SetStatus(v string) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateStatus() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) SetDailyWindowStart(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateDailyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) ClearDailyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) SetWeeklyWindowStart(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateWeeklyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) ClearWeeklyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) SetMonthlyWindowStart(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateMonthlyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserProductSubscriptionUpsertBulk) ClearMonthlyWindowStart() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) SetDailyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) AddDailyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateDailyUsageUsd() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) SetWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) AddWeeklyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateWeeklyUsageUsd() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) SetMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserProductSubscriptionUpsertBulk) AddMonthlyUsageUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateMonthlyUsageUsd() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyCarryoverInUsd sets the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsertBulk) SetDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyCarryoverInUsd(v)
	})
}

// AddDailyCarryoverInUsd adds v to the "daily_carryover_in_usd" field.
func (u *UserProductSubscriptionUpsertBulk) AddDailyCarryoverInUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyCarryoverInUsd(v)
	})
}

// UpdateDailyCarryoverInUsd sets the "daily_carryover_in_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateDailyCarryoverInUsd() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyCarryoverInUsd()
	})
}

// SetDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsertBulk) SetDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetDailyCarryoverRemainingUsd(v)
	})
}

// AddDailyCarryoverRemainingUsd adds v to the "daily_carryover_remaining_usd" field.
func (u *UserProductSubscriptionUpsertBulk) AddDailyCarryoverRemainingUsd(v float64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddDailyCarryoverRemainingUsd(v)
	})
}

// UpdateDailyCarryoverRemainingUsd sets the "daily_carryover_remaining_usd" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateDailyCarryoverRemainingUsd() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateDailyCarryoverRemainingUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserProductSubscriptionUpsertBulk) SetAssignedBy(v int64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *UserProductSubscriptionUpsertBulk) AddAssignedBy(v int64) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateAssignedBy() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserProductSubscriptionUpsertBulk) ClearAssignedBy() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserProductSubscriptionUpsertBulk) SetAssignedAt(v time.Time) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateAssignedAt() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserProductSubscriptionUpsertBulk) SetNotes(v string) *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserProductSubscriptionUpsertBulk) UpdateNotes() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserProductSubscriptionUpsertBulk) ClearNotes() *UserProductSubscriptionUpsertBulk {
	return u.Update(func(s *UserProductSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *UserProductSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserProductSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserProductSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserProductSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
