// Code generated by ent, DO NOT EDIT.

package productsubscriptionmigrationsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldID, id))
}

// ProductSubscriptionID applies equality check predicate on the "product_subscription_id" field. It's identical to ProductSubscriptionIDEQ.
func ProductSubscriptionID(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldProductSubscriptionID, v))
}

// LegacyUserSubscriptionID applies equality check predicate on the "legacy_user_subscription_id" field. It's identical to LegacyUserSubscriptionIDEQ.
func LegacyUserSubscriptionID(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyUserSubscriptionID, v))
}

// MigrationBatch applies equality check predicate on the "migration_batch" field. It's identical to MigrationBatchEQ.
func MigrationBatch(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldMigrationBatch, v))
}

// LegacyGroupID applies equality check predicate on the "legacy_group_id" field. It's identical to LegacyGroupIDEQ.
func LegacyGroupID(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyGroupID, v))
}

// LegacyStatus applies equality check predicate on the "legacy_status" field. It's identical to LegacyStatusEQ.
func LegacyStatus(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyStatus, v))
}

// LegacyStartsAt applies equality check predicate on the "legacy_starts_at" field. It's identical to LegacyStartsAtEQ.
func LegacyStartsAt(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyStartsAt, v))
}

// LegacyExpiresAt applies equality check predicate on the "legacy_expires_at" field. It's identical to LegacyExpiresAtEQ.
func LegacyExpiresAt(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyExpiresAt, v))
}

// LegacyDailyUsageUsd applies equality check predicate on the "legacy_daily_usage_usd" field. It's identical to LegacyDailyUsageUsdEQ.
func LegacyDailyUsageUsd(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyUsageUsd, v))
}

// LegacyWeeklyUsageUsd applies equality check predicate on the "legacy_weekly_usage_usd" field. It's identical to LegacyWeeklyUsageUsdEQ.
func LegacyWeeklyUsageUsd(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyMonthlyUsageUsd applies equality check predicate on the "legacy_monthly_usage_usd" field. It's identical to LegacyMonthlyUsageUsdEQ.
func LegacyMonthlyUsageUsd(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyDailyCarryoverInUsd applies equality check predicate on the "legacy_daily_carryover_in_usd" field. It's identical to LegacyDailyCarryoverInUsdEQ.
func LegacyDailyCarryoverInUsd(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverRemainingUsd applies equality check predicate on the "legacy_daily_carryover_remaining_usd" field. It's identical to LegacyDailyCarryoverRemainingUsdEQ.
func LegacyDailyCarryoverRemainingUsd(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldCreatedAt, v))
}

// ProductSubscriptionIDEQ applies the EQ predicate on the "product_subscription_id" field.
func ProductSubscriptionIDEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldProductSubscriptionID, v))
}

// ProductSubscriptionIDNEQ applies the NEQ predicate on the "product_subscription_id" field.
func ProductSubscriptionIDNEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldProductSubscriptionID, v))
}

// ProductSubscriptionIDIn applies the In predicate on the "product_subscription_id" field.
func ProductSubscriptionIDIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldProductSubscriptionID, vs...))
}

// ProductSubscriptionIDNotIn applies the NotIn predicate on the "product_subscription_id" field.
func ProductSubscriptionIDNotIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldProductSubscriptionID, vs...))
}

// LegacyUserSubscriptionIDEQ applies the EQ predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyUserSubscriptionID, v))
}

// LegacyUserSubscriptionIDNEQ applies the NEQ predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDNEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyUserSubscriptionID, v))
}

// LegacyUserSubscriptionIDIn applies the In predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyUserSubscriptionID, vs...))
}

// LegacyUserSubscriptionIDNotIn applies the NotIn predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDNotIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyUserSubscriptionID, vs...))
}

// LegacyUserSubscriptionIDGT applies the GT predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDGT(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyUserSubscriptionID, v))
}

// LegacyUserSubscriptionIDGTE applies the GTE predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDGTE(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyUserSubscriptionID, v))
}

// LegacyUserSubscriptionIDLT applies the LT predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDLT(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyUserSubscriptionID, v))
}

// LegacyUserSubscriptionIDLTE applies the LTE predicate on the "legacy_user_subscription_id" field.
func LegacyUserSubscriptionIDLTE(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyUserSubscriptionID, v))
}

// MigrationBatchEQ applies the EQ predicate on the "migration_batch" field.
func MigrationBatchEQ(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldMigrationBatch, v))
}

// MigrationBatchNEQ applies the NEQ predicate on the "migration_batch" field.
func MigrationBatchNEQ(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldMigrationBatch, v))
}

// MigrationBatchIn applies the In predicate on the "migration_batch" field.
func MigrationBatchIn(vs ...string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldMigrationBatch, vs...))
}

// MigrationBatchNotIn applies the NotIn predicate on the "migration_batch" field.
func MigrationBatchNotIn(vs ...string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldMigrationBatch, vs...))
}

// MigrationBatchGT applies the GT predicate on the "migration_batch" field.
func MigrationBatchGT(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldMigrationBatch, v))
}

// MigrationBatchGTE applies the GTE predicate on the "migration_batch" field.
func MigrationBatchGTE(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldMigrationBatch, v))
}

// MigrationBatchLT applies the LT predicate on the "migration_batch" field.
func MigrationBatchLT(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldMigrationBatch, v))
}

// MigrationBatchLTE applies the LTE predicate on the "migration_batch" field.
func MigrationBatchLTE(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldMigrationBatch, v))
}

// MigrationBatchContains applies the Contains predicate on the "migration_batch" field.
func MigrationBatchContains(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldContains(FieldMigrationBatch, v))
}

// MigrationBatchHasPrefix applies the HasPrefix predicate on the "migration_batch" field.
func MigrationBatchHasPrefix(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldHasPrefix(FieldMigrationBatch, v))
}

// MigrationBatchHasSuffix applies the HasSuffix predicate on the "migration_batch" field.
func MigrationBatchHasSuffix(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldHasSuffix(FieldMigrationBatch, v))
}

// MigrationBatchEqualFold applies the EqualFold predicate on the "migration_batch" field.
func MigrationBatchEqualFold(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEqualFold(FieldMigrationBatch, v))
}

// MigrationBatchContainsFold applies the ContainsFold predicate on the "migration_batch" field.
func MigrationBatchContainsFold(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldContainsFold(FieldMigrationBatch, v))
}

// LegacyGroupIDEQ applies the EQ predicate on the "legacy_group_id" field.
func LegacyGroupIDEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyGroupID, v))
}

// LegacyGroupIDNEQ applies the NEQ predicate on the "legacy_group_id" field.
func LegacyGroupIDNEQ(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyGroupID, v))
}

// LegacyGroupIDIn applies the In predicate on the "legacy_group_id" field.
func LegacyGroupIDIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyGroupID, vs...))
}

// LegacyGroupIDNotIn applies the NotIn predicate on the "legacy_group_id" field.
func LegacyGroupIDNotIn(vs ...int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyGroupID, vs...))
}

// LegacyGroupIDGT applies the GT predicate on the "legacy_group_id" field.
func LegacyGroupIDGT(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyGroupID, v))
}

// LegacyGroupIDGTE applies the GTE predicate on the "legacy_group_id" field.
func LegacyGroupIDGTE(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyGroupID, v))
}

// LegacyGroupIDLT applies the LT predicate on the "legacy_group_id" field.
func LegacyGroupIDLT(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyGroupID, v))
}

// LegacyGroupIDLTE applies the LTE predicate on the "legacy_group_id" field.
func LegacyGroupIDLTE(v int64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyGroupID, v))
}

// LegacyStatusEQ applies the EQ predicate on the "legacy_status" field.
func LegacyStatusEQ(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyStatus, v))
}

// LegacyStatusNEQ applies the NEQ predicate on the "legacy_status" field.
func LegacyStatusNEQ(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyStatus, v))
}

// LegacyStatusIn applies the In predicate on the "legacy_status" field.
func LegacyStatusIn(vs ...string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyStatus, vs...))
}

// LegacyStatusNotIn applies the NotIn predicate on the "legacy_status" field.
func LegacyStatusNotIn(vs ...string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyStatus, vs...))
}

// LegacyStatusGT applies the GT predicate on the "legacy_status" field.
func LegacyStatusGT(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyStatus, v))
}

// LegacyStatusGTE applies the GTE predicate on the "legacy_status" field.
func LegacyStatusGTE(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyStatus, v))
}

// LegacyStatusLT applies the LT predicate on the "legacy_status" field.
func LegacyStatusLT(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyStatus, v))
}

// LegacyStatusLTE applies the LTE predicate on the "legacy_status" field.
func LegacyStatusLTE(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyStatus, v))
}

// LegacyStatusContains applies the Contains predicate on the "legacy_status" field.
func LegacyStatusContains(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldContains(FieldLegacyStatus, v))
}

// LegacyStatusHasPrefix applies the HasPrefix predicate on the "legacy_status" field.
func LegacyStatusHasPrefix(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldHasPrefix(FieldLegacyStatus, v))
}

// LegacyStatusHasSuffix applies the HasSuffix predicate on the "legacy_status" field.
func LegacyStatusHasSuffix(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldHasSuffix(FieldLegacyStatus, v))
}

// LegacyStatusEqualFold applies the EqualFold predicate on the "legacy_status" field.
func LegacyStatusEqualFold(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEqualFold(FieldLegacyStatus, v))
}

// LegacyStatusContainsFold applies the ContainsFold predicate on the "legacy_status" field.
func LegacyStatusContainsFold(v string) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldContainsFold(FieldLegacyStatus, v))
}

// LegacyStartsAtEQ applies the EQ predicate on the "legacy_starts_at" field.
func LegacyStartsAtEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyStartsAt, v))
}

// LegacyStartsAtNEQ applies the NEQ predicate on the "legacy_starts_at" field.
func LegacyStartsAtNEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyStartsAt, v))
}

// LegacyStartsAtIn applies the In predicate on the "legacy_starts_at" field.
func LegacyStartsAtIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyStartsAt, vs...))
}

// LegacyStartsAtNotIn applies the NotIn predicate on the "legacy_starts_at" field.
func LegacyStartsAtNotIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyStartsAt, vs...))
}

// LegacyStartsAtGT applies the GT predicate on the "legacy_starts_at" field.
func LegacyStartsAtGT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyStartsAt, v))
}

// LegacyStartsAtGTE applies the GTE predicate on the "legacy_starts_at" field.
func LegacyStartsAtGTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyStartsAt, v))
}

// LegacyStartsAtLT applies the LT predicate on the "legacy_starts_at" field.
func LegacyStartsAtLT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyStartsAt, v))
}

// LegacyStartsAtLTE applies the LTE predicate on the "legacy_starts_at" field.
func LegacyStartsAtLTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyStartsAt, v))
}

// LegacyExpiresAtEQ applies the EQ predicate on the "legacy_expires_at" field.
func LegacyExpiresAtEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyExpiresAt, v))
}

// LegacyExpiresAtNEQ applies the NEQ predicate on the "legacy_expires_at" field.
func LegacyExpiresAtNEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyExpiresAt, v))
}

// LegacyExpiresAtIn applies the In predicate on the "legacy_expires_at" field.
func LegacyExpiresAtIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyExpiresAt, vs...))
}

// LegacyExpiresAtNotIn applies the NotIn predicate on the "legacy_expires_at" field.
func LegacyExpiresAtNotIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyExpiresAt, vs...))
}

// LegacyExpiresAtGT applies the GT predicate on the "legacy_expires_at" field.
func LegacyExpiresAtGT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyExpiresAt, v))
}

// LegacyExpiresAtGTE applies the GTE predicate on the "legacy_expires_at" field.
func LegacyExpiresAtGTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyExpiresAt, v))
}

// LegacyExpiresAtLT applies the LT predicate on the "legacy_expires_at" field.
func LegacyExpiresAtLT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyExpiresAt, v))
}

// LegacyExpiresAtLTE applies the LTE predicate on the "legacy_expires_at" field.
func LegacyExpiresAtLTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyExpiresAt, v))
}

// LegacyDailyUsageUsdEQ applies the EQ predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyUsageUsd, v))
}

// LegacyDailyUsageUsdNEQ applies the NEQ predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdNEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyDailyUsageUsd, v))
}

// LegacyDailyUsageUsdIn applies the In predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyDailyUsageUsd, vs...))
}

// LegacyDailyUsageUsdNotIn applies the NotIn predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdNotIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyDailyUsageUsd, vs...))
}

// LegacyDailyUsageUsdGT applies the GT predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdGT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyDailyUsageUsd, v))
}

// LegacyDailyUsageUsdGTE applies the GTE predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdGTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyDailyUsageUsd, v))
}

// LegacyDailyUsageUsdLT applies the LT predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdLT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyDailyUsageUsd, v))
}

// LegacyDailyUsageUsdLTE applies the LTE predicate on the "legacy_daily_usage_usd" field.
func LegacyDailyUsageUsdLTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyDailyUsageUsd, v))
}

// LegacyWeeklyUsageUsdEQ applies the EQ predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyWeeklyUsageUsdNEQ applies the NEQ predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdNEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyWeeklyUsageUsdIn applies the In predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyWeeklyUsageUsd, vs...))
}

// LegacyWeeklyUsageUsdNotIn applies the NotIn predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdNotIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyWeeklyUsageUsd, vs...))
}

// LegacyWeeklyUsageUsdGT applies the GT predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdGT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyWeeklyUsageUsdGTE applies the GTE predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdGTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyWeeklyUsageUsdLT applies the LT predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdLT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyWeeklyUsageUsdLTE applies the LTE predicate on the "legacy_weekly_usage_usd" field.
func LegacyWeeklyUsageUsdLTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyWeeklyUsageUsd, v))
}

// LegacyMonthlyUsageUsdEQ applies the EQ predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyMonthlyUsageUsdNEQ applies the NEQ predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdNEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyMonthlyUsageUsdIn applies the In predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyMonthlyUsageUsd, vs...))
}

// LegacyMonthlyUsageUsdNotIn applies the NotIn predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdNotIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyMonthlyUsageUsd, vs...))
}

// LegacyMonthlyUsageUsdGT applies the GT predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdGT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyMonthlyUsageUsdGTE applies the GTE predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdGTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyMonthlyUsageUsdLT applies the LT predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdLT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyMonthlyUsageUsdLTE applies the LTE predicate on the "legacy_monthly_usage_usd" field.
func LegacyMonthlyUsageUsdLTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyMonthlyUsageUsd, v))
}

// LegacyDailyCarryoverInUsdEQ applies the EQ predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverInUsdNEQ applies the NEQ predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdNEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverInUsdIn applies the In predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyDailyCarryoverInUsd, vs...))
}

// LegacyDailyCarryoverInUsdNotIn applies the NotIn predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdNotIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyDailyCarryoverInUsd, vs...))
}

// LegacyDailyCarryoverInUsdGT applies the GT predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdGT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverInUsdGTE applies the GTE predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdGTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverInUsdLT applies the LT predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdLT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverInUsdLTE applies the LTE predicate on the "legacy_daily_carryover_in_usd" field.
func LegacyDailyCarryoverInUsdLTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyDailyCarryoverInUsd, v))
}

// LegacyDailyCarryoverRemainingUsdEQ applies the EQ predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// LegacyDailyCarryoverRemainingUsdNEQ applies the NEQ predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdNEQ(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// LegacyDailyCarryoverRemainingUsdIn applies the In predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldLegacyDailyCarryoverRemainingUsd, vs...))
}

// LegacyDailyCarryoverRemainingUsdNotIn applies the NotIn predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdNotIn(vs ...float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldLegacyDailyCarryoverRemainingUsd, vs...))
}

// LegacyDailyCarryoverRemainingUsdGT applies the GT predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdGT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// LegacyDailyCarryoverRemainingUsdGTE applies the GTE predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdGTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// LegacyDailyCarryoverRemainingUsdLT applies the LT predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdLT(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// LegacyDailyCarryoverRemainingUsdLTE applies the LTE predicate on the "legacy_daily_carryover_remaining_usd" field.
func LegacyDailyCarryoverRemainingUsdLTE(v float64) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldLegacyDailyCarryoverRemainingUsd, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProductSubscription applies the HasEdge predicate on the "product_subscription" edge.
func HasProductSubscription() predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductSubscriptionTable, ProductSubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductSubscriptionWith applies the HasEdge predicate on the "product_subscription" edge with a given conditions (other predicates).
func HasProductSubscriptionWith(preds ...predicate.UserProductSubscription) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(func(s *sql.Selector) {
		step := newProductSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductSubscriptionMigrationSource) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductSubscriptionMigrationSource) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductSubscriptionMigrationSource) predicate.ProductSubscriptionMigrationSource {
	return predicate.ProductSubscriptionMigrationSource(sql.NotPredicates(p))
}
