// Code generated by ent, DO NOT EDIT.

package userproductsubscription

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userproductsubscription type in the database.
	Label = "user_product_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDailyWindowStart holds the string denoting the daily_window_start field in the database.
	FieldDailyWindowStart = "daily_window_start"
	// FieldWeeklyWindowStart holds the string denoting the weekly_window_start field in the database.
	FieldWeeklyWindowStart = "weekly_window_start"
	// FieldMonthlyWindowStart holds the string denoting the monthly_window_start field in the database.
	FieldMonthlyWindowStart = "monthly_window_start"
	// FieldDailyUsageUsd holds the string denoting the daily_usage_usd field in the database.
	FieldDailyUsageUsd = "daily_usage_usd"
	// FieldWeeklyUsageUsd holds the string denoting the weekly_usage_usd field in the database.
	FieldWeeklyUsageUsd = "weekly_usage_usd"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// FieldDailyCarryoverInUsd holds the string denoting the daily_carryover_in_usd field in the database.
	FieldDailyCarryoverInUsd = "daily_carryover_in_usd"
	// FieldDailyCarryoverRemainingUsd holds the string denoting the daily_carryover_remaining_usd field in the database.
	FieldDailyCarryoverRemainingUsd = "daily_carryover_remaining_usd"
	// FieldAssignedBy holds the string denoting the assigned_by field in the database.
	FieldAssignedBy = "assigned_by"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeMigrationSources holds the string denoting the migration_sources edge name in mutations.
	EdgeMigrationSources = "migration_sources"
	// Table holds the table name of the userproductsubscription in the database.
	Table = "user_product_subscriptions"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "user_product_subscriptions"
	// ProductInverseTable is the table name for the SubscriptionProduct entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionproduct" package.
	ProductInverseTable = "subscription_products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// MigrationSourcesTable is the table that holds the migration_sources relation/edge.
	MigrationSourcesTable = "product_subscription_migration_sources"
	// MigrationSourcesInverseTable is the table name for the ProductSubscriptionMigrationSource entity.
	// It exists in this package in order to avoid circular dependency with the "productsubscriptionmigrationsource" package.
	MigrationSourcesInverseTable = "product_subscription_migration_sources"
	// MigrationSourcesColumn is the table column denoting the migration_sources relation/edge.
	MigrationSourcesColumn = "product_subscription_id"
)

// Columns holds all SQL columns for userproductsubscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldProductID,
	FieldStartsAt,
	FieldExpiresAt,
	FieldStatus,
	FieldDailyWindowStart,
	FieldWeeklyWindowStart,
	FieldMonthlyWindowStart,
	FieldDailyUsageUsd,
	FieldWeeklyUsageUsd,
	FieldMonthlyUsageUsd,
	FieldDailyCarryoverInUsd,
	FieldDailyCarryoverRemainingUsd,
	FieldAssignedBy,
	FieldAssignedAt,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultDailyUsageUsd holds the default value on creation for the "daily_usage_usd" field.
	DefaultDailyUsageUsd float64
	// DefaultWeeklyUsageUsd holds the default value on creation for the "weekly_usage_usd" field.
	DefaultWeeklyUsageUsd float64
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd float64
	// DefaultDailyCarryoverInUsd holds the default value on creation for the "daily_carryover_in_usd" field.
	DefaultDailyCarryoverInUsd float64
	// DefaultDailyCarryoverRemainingUsd holds the default value on creation for the "daily_carryover_remaining_usd" field.
	DefaultDailyCarryoverRemainingUsd float64
	// DefaultAssignedAt holds the default value on creation for the "assigned_at" field.
	DefaultAssignedAt func() time.Time
)

// OrderOption defines the ordering options for the UserProductSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDailyWindowStart orders the results by the daily_window_start field.
func ByDailyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyWindowStart, opts...).ToFunc()
}

// ByWeeklyWindowStart orders the results by the weekly_window_start field.
func ByWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyWindowStart, opts...).ToFunc()
}

// ByMonthlyWindowStart orders the results by the monthly_window_start field.
func ByMonthlyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyWindowStart, opts...).ToFunc()
}

// ByDailyUsageUsd orders the results by the daily_usage_usd field.
func ByDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageUsd, opts...).ToFunc()
}

// ByWeeklyUsageUsd orders the results by the weekly_usage_usd field.
func ByWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyUsageUsd, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// ByDailyCarryoverInUsd orders the results by the daily_carryover_in_usd field.
func ByDailyCarryoverInUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyCarryoverInUsd, opts...).ToFunc()
}

// ByDailyCarryoverRemainingUsd orders the results by the daily_carryover_remaining_usd field.
func ByDailyCarryoverRemainingUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyCarryoverRemainingUsd, opts...).ToFunc()
}

// ByAssignedBy orders the results by the assigned_by field.
func ByAssignedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedBy, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// ByMigrationSourcesCount orders the results by migration_sources count.
func ByMigrationSourcesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMigrationSourcesStep(), opts...)
	}
}

// ByMigrationSources orders the results by migration_sources terms.
func ByMigrationSources(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMigrationSourcesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newMigrationSourcesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MigrationSourcesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MigrationSourcesTable, MigrationSourcesColumn),
	)
}
