// Code generated by ent, DO NOT EDIT.

package inviterelationshipevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inviterelationshipevent type in the database.
	Label = "invite_relationship_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldPreviousInviterUserID holds the string denoting the previous_inviter_user_id field in the database.
	FieldPreviousInviterUserID = "previous_inviter_user_id"
	// FieldNewInviterUserID holds the string denoting the new_inviter_user_id field in the database.
	FieldNewInviterUserID = "new_inviter_user_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldEffectiveAt holds the string denoting the effective_at field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the inviterelationshipevent in the database.
	Table = "invite_relationship_events"
)

// Columns holds all SQL columns for inviterelationshipevent fields.
var Columns = []string{
	FieldID,
	FieldInviteeUserID,
	FieldPreviousInviterUserID,
	FieldNewInviterUserID,
	FieldEventType,
	FieldEffectiveAt,
	FieldOperatorUserID,
	FieldReason,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InviteRelationshipEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByPreviousInviterUserID orders the results by the previous_inviter_user_id field.
func ByPreviousInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousInviterUserID, opts...).ToFunc()
}

// ByNewInviterUserID orders the results by the new_inviter_user_id field.
func ByNewInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewInviterUserID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effective_at field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
