// Code generated by ent, DO NOT EDIT.

package inviterewardrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inviterewardrecord type in the database.
	Label = "invite_reward_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldTriggerRedeemCodeID holds the string denoting the trigger_redeem_code_id field in the database.
	FieldTriggerRedeemCodeID = "trigger_redeem_code_id"
	// FieldTriggerRedeemCodeValue holds the string denoting the trigger_redeem_code_value field in the database.
	FieldTriggerRedeemCodeValue = "trigger_redeem_code_value"
	// FieldRewardTargetUserID holds the string denoting the reward_target_user_id field in the database.
	FieldRewardTargetUserID = "reward_target_user_id"
	// FieldRewardRole holds the string denoting the reward_role field in the database.
	FieldRewardRole = "reward_role"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldRewardRate holds the string denoting the reward_rate field in the database.
	FieldRewardRate = "reward_rate"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldAdminActionID holds the string denoting the admin_action_id field in the database.
	FieldAdminActionID = "admin_action_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the inviterewardrecord in the database.
	Table = "invite_reward_records"
)

// Columns holds all SQL columns for inviterewardrecord fields.
var Columns = []string{
	FieldID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldTriggerRedeemCodeID,
	FieldTriggerRedeemCodeValue,
	FieldRewardTargetUserID,
	FieldRewardRole,
	FieldRewardType,
	FieldRewardRate,
	FieldRewardAmount,
	FieldStatus,
	FieldNotes,
	FieldAdminActionID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RewardRoleValidator is a validator for the "reward_role" field. It is called by the builders before save.
	RewardRoleValidator func(string) error
	// RewardTypeValidator is a validator for the "reward_type" field. It is called by the builders before save.
	RewardTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InviteRewardRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByTriggerRedeemCodeID orders the results by the trigger_redeem_code_id field.
func ByTriggerRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerRedeemCodeID, opts...).ToFunc()
}

// ByTriggerRedeemCodeValue orders the results by the trigger_redeem_code_value field.
func ByTriggerRedeemCodeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerRedeemCodeValue, opts...).ToFunc()
}

// ByRewardTargetUserID orders the results by the reward_target_user_id field.
func ByRewardTargetUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardTargetUserID, opts...).ToFunc()
}

// ByRewardRole orders the results by the reward_role field.
func ByRewardRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardRole, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// ByRewardRate orders the results by the reward_rate field.
func ByRewardRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardRate, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByAdminActionID orders the results by the admin_action_id field.
func ByAdminActionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminActionID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
