// Code generated by ent, DO NOT EDIT.

package inviteadminaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inviteadminaction type in the database.
	Label = "invite_admin_action"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldTargetUserID holds the string denoting the target_user_id field in the database.
	FieldTargetUserID = "target_user_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldRequestSnapshotJSON holds the string denoting the request_snapshot_json field in the database.
	FieldRequestSnapshotJSON = "request_snapshot_json"
	// FieldResultSnapshotJSON holds the string denoting the result_snapshot_json field in the database.
	FieldResultSnapshotJSON = "result_snapshot_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the inviteadminaction in the database.
	Table = "invite_admin_actions"
)

// Columns holds all SQL columns for inviteadminaction fields.
var Columns = []string{
	FieldID,
	FieldActionType,
	FieldOperatorUserID,
	FieldTargetUserID,
	FieldReason,
	FieldRequestSnapshotJSON,
	FieldResultSnapshotJSON,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	ActionTypeValidator func(string) error
	// DefaultRequestSnapshotJSON holds the default value on creation for the "request_snapshot_json" field.
	DefaultRequestSnapshotJSON func() map[string]interface{}
	// DefaultResultSnapshotJSON holds the default value on creation for the "result_snapshot_json" field.
	DefaultResultSnapshotJSON func() map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InviteAdminAction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByTargetUserID orders the results by the target_user_id field.
func ByTargetUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetUserID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
